import type { Project } from '../../types/domain'
import type {
  CandidateTemplateMix,
  SelectionHandoffSnapshot,
} from '../../types/selection'
import type {
  AcceptanceCriterion,
  BusinessRule,
  DataFieldDefinition,
  ExceptionScenario,
  FeatureEvidenceRef,
  FeatureScope,
  KpiDefinition,
  KpiDirection,
  MvpAiFeature,
  MvpDataEntity,
  MvpFeature,
  MvpIntegration,
  MvpRole,
  MvpScreen,
  MvpWorkflow,
  MvpWorkflowStep,
  PermissionRule,
  RolePermissionAction,
  ScreenComponentDefinition,
  ScreenType,
  TestScenario,
} from '../../types/mvpDesign'
import type { FeatureBlueprint } from './featureBlueprints'
import { TEMPLATE_BLUEPRINTS } from './featureBlueprints'

export interface GeneratedDesign {
  workflows: MvpWorkflow[]
  roles: MvpRole[]
  entities: MvpDataEntity[]
  features: MvpFeature[]
  screens: MvpScreen[]
  permissions: PermissionRule[]
  businessRules: BusinessRule[]
  aiFeatures: MvpAiFeature[]
  integrations: MvpIntegration[]
  exceptions: ExceptionScenario[]
  acceptanceCriteria: AcceptanceCriterion[]
  testScenarios: TestScenario[]
  kpis: KpiDefinition[]
}

/* 텍스트를 결정적으로 단계로 분해한다 (random/시간 미사용) */
function splitSteps(text: string): string[] {
  if (!text.trim()) return []
  return text
    .split(/→|\n|\.|·|,|;/)
    .map((s) => s.trim())
    .filter((s) => s.length > 1)
    .slice(0, 6)
}

function downgradeScope(scope: FeatureScope): FeatureScope {
  if (scope === 'must') return 'should'
  if (scope === 'should') return 'later'
  return scope
}

function evidenceFor(handoff: SelectionHandoffSnapshot, template: string | null): FeatureEvidenceRef[] {
  const refs: FeatureEvidenceRef[] = []
  if (handoff.primaryCandidate) {
    refs.push({ kind: 'candidate', label: `확정 핵심 과제: ${handoff.primaryCandidate.name}`, sourceId: handoff.primaryCandidate.candidateId })
  }
  if (template) {
    refs.push({ kind: 'template', label: `추천 템플릿 구성: ${template}`, sourceId: template })
  }
  return refs
}

interface FeaturePick {
  blueprint: FeatureBlueprint
  scope: FeatureScope
  template: CandidateTemplateMix['template']
}

/** templateMix를 기반으로 기능 청사진을 결정적으로 선택한다 */
function pickFeatures(templateMix: CandidateTemplateMix[]): FeaturePick[] {
  const sorted = [...templateMix].sort((a, b) => b.percentage - a.percentage || a.template.localeCompare(b.template))
  const seen = new Set<string>()
  const picks: FeaturePick[] = []
  sorted.forEach((mix, ti) => {
    const blueprint = TEMPLATE_BLUEPRINTS[mix.template]
    if (!blueprint) return
    blueprint.features.forEach((feature) => {
      if (seen.has(feature.name)) return
      seen.add(feature.name)
      let scope = feature.defaultScope
      if (ti === 1) scope = downgradeScope(scope)
      else if (ti >= 2) scope = 'later'
      picks.push({ blueprint: feature, scope, template: mix.template })
    })
  })
  return picks
}

function buildRoles(handoff: SelectionHandoffSnapshot, hasApproval: boolean): MvpRole[] {
  const roles: MvpRole[] = []
  const primaryUsers = handoff.targetUsers.trim() || '현업 담당자'
  roles.push({
    id: 'role-user',
    name: '현업 담당자',
    description: '핵심 업무를 직접 수행하는 실사용자입니다.',
    sourceUsers: primaryUsers,
    isPrimaryUser: true,
    order: 0,
    autoGenerated: true,
  })
  if (hasApproval) {
    roles.push({
      id: 'role-approver',
      name: '승인자',
      description: '요청을 승인·반려하는 관리자입니다.',
      sourceUsers: '팀장·관리자',
      isPrimaryUser: false,
      order: 1,
      autoGenerated: true,
    })
  }
  roles.push({
    id: 'role-admin',
    name: '운영 관리자',
    description: '기준값·구성원 등 최소한의 운영 설정을 관리합니다.',
    sourceUsers: '운영 담당',
    isPrimaryUser: false,
    order: roles.length,
    autoGenerated: true,
  })
  return roles
}

function buildEntities(picks: FeaturePick[]): { entities: MvpDataEntity[]; keyToId: Map<string, string> } {
  const keyToId = new Map<string, string>()
  const entities: MvpDataEntity[] = []
  const usedKeys = new Set<string>()
  picks
    .filter((p) => p.scope === 'must' || p.scope === 'should')
    .forEach((p) => p.blueprint.entityKeys.forEach((k) => usedKeys.add(`${p.template}::${k}`)))

  let order = 0
  for (const composite of usedKeys) {
    const [template, key] = composite.split('::')
    const blueprint = TEMPLATE_BLUEPRINTS[template as CandidateTemplateMix['template']]
    const entBp = blueprint?.entities.find((e) => e.key === key)
    if (!entBp) continue
    const id = `ent-${order}`
    keyToId.set(composite, id)
    const fields: DataFieldDefinition[] = entBp.fields.map((f, fi) => ({
      id: `${id}-f${fi}`,
      name: f.name,
      label: f.label,
      type: f.type,
      required: f.required,
      detail: f.detail,
      sensitive: f.sensitive,
      computedFrom: f.computedFrom,
    }))
    entities.push({
      id,
      name: entBp.name,
      label: entBp.label,
      description: entBp.description,
      fields,
      ownedByFeatureIds: [],
      hasSensitiveData: fields.some((f) => f.sensitive),
      order,
      autoGenerated: true,
    })
    order += 1
  }
  return { entities, keyToId }
}

const SCREEN_TYPE_BY_FEATURE: Record<string, ScreenType> = {
  input_form: 'form',
  list_view: 'list',
  detail_view: 'detail',
  rule_calculation: 'result',
  document_generation: 'result',
  approval_flow: 'detail',
  notification: 'list',
  dashboard_report: 'dashboard',
  search_filter: 'list',
  data_validation: 'result',
  status_tracking: 'dashboard',
  ai_assist: 'result',
  integration: 'setting',
  admin_setting: 'setting',
  other: 'detail',
}

function screenComponents(feature: MvpFeature): ScreenComponentDefinition[] {
  const base: ScreenComponentDefinition[] = []
  const sid = feature.id
  if (feature.type === 'input_form') {
    base.push({ id: `${sid}-c0`, label: '입력 폼', kind: 'form_field', description: feature.input })
    base.push({ id: `${sid}-c1`, label: '저장 버튼', kind: 'button', description: '검증 후 저장' })
  } else if (feature.type === 'list_view' || feature.type === 'search_filter' || feature.type === 'status_tracking') {
    base.push({ id: `${sid}-c0`, label: '검색·필터', kind: 'filter', description: '조건별 조회' })
    base.push({ id: `${sid}-c1`, label: '목록 표', kind: 'table', description: feature.output })
  } else if (feature.type === 'dashboard_report') {
    base.push({ id: `${sid}-c0`, label: '요약 카드', kind: 'summary_card', description: feature.output })
    base.push({ id: `${sid}-c1`, label: '현황 차트', kind: 'chart', description: '상태·추이 요약' })
  } else {
    base.push({ id: `${sid}-c0`, label: '결과 표시', kind: 'text', description: feature.output })
    base.push({ id: `${sid}-c1`, label: '상태 배지', kind: 'status', description: '처리 상태' })
  }
  return base
}

/** 핵심 과제 → 실제 설계 산출물을 결정적으로 생성한다 */
export function generateDesign(
  handoff: SelectionHandoffSnapshot,
  _project: Project,
): GeneratedDesign {
  const picks = pickFeatures(handoff.templateMix)
  const hasApproval = picks.some((p) => p.blueprint.type === 'approval_flow')

  const roles = buildRoles(handoff, hasApproval)
  const primaryRoleId = roles[0].id
  const approverRoleId = roles.find((r) => r.id === 'role-approver')?.id ?? primaryRoleId
  const { entities, keyToId } = buildEntities(picks)

  /* 기능 */
  const features: MvpFeature[] = picks.map((pick, i) => {
    const bp = pick.blueprint
    const id = `feat-${i}`
    const entityIds = bp.entityKeys
      .map((k) => keyToId.get(`${pick.template}::${k}`))
      .filter((v): v is string => v !== undefined)
    return {
      id,
      name: bp.name,
      summary: bp.summary,
      scope: pick.scope,
      scopeReason: '',
      type: bp.type,
      automationMode: bp.automationMode,
      input: bp.input,
      processing: bp.processing,
      processingKind: bp.processingKind,
      output: bp.output,
      screenIds: [],
      entityIds,
      businessRuleIds: [],
      usesAi: false,
      humanReviewRequired: bp.humanReviewRequired,
      expertJudgmentBoundary: bp.expertJudgmentBoundary,
      evidence: evidenceFor(handoff, pick.template),
      sourceTemplate: pick.template,
      autoGenerated: true,
      order: i,
    }
  })

  // 엔티티 소유 기능 역참조
  features.forEach((f) => f.entityIds.forEach((eid) => {
    const ent = entities.find((e) => e.id === eid)
    if (ent && !ent.ownedByFeatureIds.includes(f.id)) ent.ownedByFeatureIds.push(f.id)
  }))

  /* 업무 규칙 (기능 청사진 기반) */
  const businessRules: BusinessRule[] = []
  picks.forEach((pick, i) => {
    const featureId = features[i].id
    pick.blueprint.rules.forEach((rule, ri) => {
      const rid = `rule-${i}-${ri}`
      businessRules.push({
        id: rid,
        name: rule.name,
        type: rule.type,
        condition: rule.condition,
        outcome: rule.outcome,
        needsConfirmation: rule.needsConfirmation,
        evidence: evidenceFor(handoff, pick.template),
        featureId,
        autoGenerated: true,
        order: businessRules.length,
      })
      features[i].businessRuleIds.push(rid)
    })
  })

  /* 화면 (기능 유형별로 묶어 화면 수를 절제) */
  const screens: MvpScreen[] = []
  const screenByType = new Map<ScreenType, MvpScreen>()
  features
    .filter((f) => f.scope === 'must' || f.scope === 'should')
    .forEach((f) => {
      const stype = SCREEN_TYPE_BY_FEATURE[f.type] ?? 'detail'
      let screen = screenByType.get(stype)
      if (!screen) {
        screen = {
          id: `scr-${screens.length}`,
          name: SCREEN_NAME_BY_TYPE[stype],
          type: stype,
          purpose: '',
          primaryRoleId,
          components: [],
          featureIds: [],
          scope: f.scope,
          order: screens.length,
          autoGenerated: true,
        }
        screenByType.set(stype, screen)
        screens.push(screen)
      }
      screen.featureIds.push(f.id)
      screen.components.push(...screenComponents(f))
      if (f.scope === 'must') screen.scope = 'must'
      f.screenIds.push(screen.id)
    })
  screens.forEach((s) => {
    s.purpose = `${s.featureIds.length}개 기능을 담는 ${SCREEN_NAME_BY_TYPE[s.type]} 화면입니다.`
  })

  /* 권한 (역할 × 엔티티) */
  const permissions: PermissionRule[] = []
  entities.forEach((ent) => {
    permissions.push({
      id: `perm-${primaryRoleId}-${ent.id}`,
      roleId: primaryRoleId,
      entityId: ent.id,
      actions: ['create', 'read', 'update'] as RolePermissionAction[],
      condition: ent.hasSensitiveData ? '민감정보는 담당 건만 조회' : '',
    })
    if (hasApproval) {
      permissions.push({
        id: `perm-${approverRoleId}-${ent.id}`,
        roleId: approverRoleId,
        entityId: ent.id,
        actions: ['read', 'approve'] as RolePermissionAction[],
        condition: '승인 대기 건 한정',
      })
    }
    permissions.push({
      id: `perm-role-admin-${ent.id}`,
      roleId: 'role-admin',
      entityId: ent.id,
      actions: ['read', 'export'] as RolePermissionAction[],
      condition: '',
    })
  })

  /* AI 기능 — 필요할 때만, 최대 2개 */
  const aiFeatures = buildAiFeatures(handoff, features)
  aiFeatures.forEach((ai) => {
    if (ai.featureId) {
      const f = features.find((x) => x.id === ai.featureId)
      if (f) f.usesAi = true
    }
  })

  /* 외부 연동 — 의존성에서만 도출 */
  const integrations: MvpIntegration[] = handoff.dependencies
    .filter((d) => d.type === 'external_system')
    .map((d, i) => ({
      id: `intg-${i}`,
      name: d.title,
      target: d.title,
      purpose: d.description || '외부 시스템 연동',
      readiness: d.resolved ? 'ready' : 'needs_setup',
      fallbackWhenNotReady: d.resolved ? '' : '연동 전에는 수기 입력·CSV 업로드로 대체합니다.',
      requiredBeforeMvp: d.requiredBeforeMvp,
      order: i,
    }))

  /* 예외 시나리오 */
  const exceptions = buildExceptions(features)

  /* 수용 기준 (Must 기능) */
  const acceptanceCriteria = buildAcceptance(features)

  /* 테스트 시나리오 (Must 기능) */
  const testScenarios = buildTests(features)

  /* KPI */
  const kpis = buildKpis(handoff)

  /* 업무 흐름 */
  const workflows = buildWorkflows(handoff, features)

  return {
    workflows,
    roles,
    entities,
    features,
    screens,
    permissions,
    businessRules,
    aiFeatures,
    integrations,
    exceptions,
    acceptanceCriteria,
    testScenarios,
    kpis,
  }
}

const SCREEN_NAME_BY_TYPE: Record<ScreenType, string> = {
  list: '목록·검색',
  detail: '상세·처리',
  form: '입력',
  dashboard: '현황 대시보드',
  wizard: '단계 입력',
  result: '결과·확정',
  setting: '설정',
  auth: '로그인',
}

function buildAiFeatures(handoff: SelectionHandoffSnapshot, features: MvpFeature[]): MvpAiFeature[] {
  const necessity = handoff.primaryCandidate?.aiNecessity ?? 'unnecessary'
  if (necessity === 'unnecessary' || necessity === 'not_applicable') return []
  const result: MvpAiFeature[] = []
  const docFeature = features.find((f) => f.type === 'document_generation' && (f.scope === 'must' || f.scope === 'should'))
  if (docFeature) {
    result.push({
      id: 'ai-0',
      name: '문서 초안 AI 보조',
      purpose: 'draft_generation',
      justification: '정형 양식 밖의 자유서술 문장을 만들어야 해 규칙만으로는 부족합니다.',
      humanConfirms: true,
      expertJudgmentBoundary: false,
      fallback: 'AI 미사용 시 표준 문구 템플릿으로 대체합니다.',
      featureId: docFeature.id,
      order: 0,
    })
  }
  if (result.length < 2 && (necessity === 'useful')) {
    const classifyFeature = features.find((f) => (f.type === 'data_validation' || f.type === 'status_tracking') && f.scope !== 'excluded')
    if (classifyFeature) {
      result.push({
        id: 'ai-1',
        name: '문의·항목 자동 분류 보조',
        purpose: 'classification',
        justification: '비정형 입력을 유형별로 분류해 처리 속도를 높입니다.',
        humanConfirms: true,
        expertJudgmentBoundary: false,
        fallback: '분류 규칙표 기반 수동 선택으로 대체합니다.',
        featureId: classifyFeature.id,
        order: 1,
      })
    }
  }
  return result
}

function buildExceptions(features: MvpFeature[]): ExceptionScenario[] {
  const list: ExceptionScenario[] = []
  const mustFeatures = features.filter((f) => f.scope === 'must')
  mustFeatures.slice(0, 4).forEach((f) => {
    if (f.type === 'input_form') {
      list.push({ id: `exc-${list.length}`, kind: 'invalid_input', situation: `${f.name}에서 필수·형식 오류 입력`, handling: '저장을 막고 오류 항목을 표시한다.', featureId: f.id, order: list.length })
    } else {
      list.push({ id: `exc-${list.length}`, kind: 'missing_data', situation: `${f.name} 처리에 필요한 데이터 누락`, handling: '처리를 보류하고 누락 항목을 안내한다.', featureId: f.id, order: list.length })
    }
  })
  if (features.some((f) => f.expertJudgmentBoundary)) {
    list.push({ id: `exc-${list.length}`, kind: 'expert_required', situation: '전문가 최종판단이 필요한 조건 발생', handling: '자동 처리하지 않고 담당 전문가 확인 대상으로 표시한다.', featureId: null, order: list.length })
  }
  list.push({ id: `exc-${list.length}`, kind: 'permission_denied', situation: '권한 없는 역할이 민감 데이터 접근', handling: '접근을 차단하고 사유를 기록한다.', featureId: null, order: list.length })
  return list
}

function buildAcceptance(features: MvpFeature[]): AcceptanceCriterion[] {
  const list: AcceptanceCriterion[] = []
  features
    .filter((f) => f.scope === 'must')
    .forEach((f) => {
      list.push({
        id: `ac-${list.length}`,
        featureId: f.id,
        given: `${f.input}이(가) 준비된 상태에서`,
        when: `${f.name}을(를) 실행하면`,
        then: `${f.output}이(가) 생성된다`,
        measurable: true,
        order: list.length,
      })
      if (f.type === 'input_form' || f.type === 'data_validation') {
        list.push({
          id: `ac-${list.length}`,
          featureId: f.id,
          given: '필수 항목이 비어 있거나 형식이 잘못된 상태에서',
          when: `${f.name}을(를) 실행하면`,
          then: '저장·처리가 막히고 오류 항목이 표시된다',
          measurable: true,
          order: list.length,
        })
      }
    })
  return list
}

function buildTests(features: MvpFeature[]): TestScenario[] {
  const list: TestScenario[] = []
  features
    .filter((f) => f.scope === 'must')
    .forEach((f) => {
      list.push({
        id: `test-${list.length}`,
        title: `${f.name} 정상 흐름`,
        kind: 'happy_path',
        steps: [`${f.input} 입력`, `${f.name} 실행`],
        expected: `${f.output} 생성 확인`,
        featureId: f.id,
        order: list.length,
      })
      if (f.humanReviewRequired) {
        list.push({
          id: `test-${list.length}`,
          title: `${f.name} 사람 확정 검증`,
          kind: 'validation',
          steps: ['자동 결과 초안 확인', '담당자 수정·확정'],
          expected: '확정 전에는 최종 상태로 넘어가지 않음',
          featureId: f.id,
          order: list.length,
        })
      }
    })
  return list
}

function guessDirection(text: string): KpiDirection {
  if (/절감|감소|단축|축소|줄/.test(text)) return 'decrease'
  if (/증가|향상|확대|개선|상승/.test(text)) return 'increase'
  return 'maintain'
}

function buildKpis(handoff: SelectionHandoffSnapshot): KpiDefinition[] {
  return handoff.expectedKpis.slice(0, 5).map((kpi, i) => ({
    id: `kpi-${i}`,
    name: kpi,
    direction: guessDirection(kpi),
    baseline: '',
    target: '',
    unit: '',
    measureMethod: '검증 단계에서 사용 로그·담당자 확인으로 측정',
    notEstimable: true,
    sourceKpi: kpi,
    order: i,
  }))
}

function buildWorkflows(handoff: SelectionHandoffSnapshot, features: MvpFeature[]): MvpWorkflow[] {
  const currentSteps: MvpWorkflowStep[] = splitSteps(handoff.currentWorkflow).map((action, i) => ({
    id: `wf-cur-${i}`,
    order: i,
    actor: handoff.targetUsers.trim() || '담당자',
    action,
    handledBy: 'user',
    featureId: null,
    note: '',
  }))
  const mustFeatures = features.filter((f) => f.scope === 'must')
  const desiredRaw = splitSteps(handoff.desiredWorkflow)
  const desiredSource = desiredRaw.length > 0 ? desiredRaw : mustFeatures.map((f) => f.name)
  const desiredSteps: MvpWorkflowStep[] = desiredSource.map((action, i) => {
    const linked = mustFeatures[i] ?? null
    const handledBy: MvpWorkflowStep['handledBy'] = linked
      ? linked.automationMode === 'full_auto'
        ? 'system'
        : 'system_and_user'
      : 'user'
    return {
      id: `wf-des-${i}`,
      order: i,
      actor: handoff.targetUsers.trim() || '담당자',
      action,
      handledBy,
      featureId: linked?.id ?? null,
      note: '',
    }
  })
  return [
    { kind: 'current', summary: handoff.currentWorkflow || '현재 업무 흐름 미기재', steps: currentSteps },
    { kind: 'desired', summary: handoff.desiredWorkflow || 'MVP 적용 후 목표 흐름', steps: desiredSteps },
  ]
}
