import type { Project } from '../types/domain'
import type {
  AnalysisIssue,
  AssessmentDomain,
  AssessmentResult,
  InterviewQuestion,
  ManualScoreAdjustment,
} from '../types/assessment'
import {
  activityRepository,
  analysisIssueRepository,
  assessmentRepository,
  interviewQuestionRepository,
  projectRepository,
  surveyResponseRepository,
} from '../repositories'
import { CURRENT_USER } from '../data/demo'
import { RECOMMENDATION_META } from '../lib/assessmentMeta'
import { DEDUCTION_TYPE_LABEL } from './assessment/deductionLabels'
import { gatherAnalysisDataset } from './assessment/analysisData'
import {
  computeSnapshotHash,
  runAssessmentAnalysis,
} from './assessment/assessmentOrchestrator'
import { recommendationForScore } from './assessment/scoringConfig'

function nowIso(): string {
  return new Date().toISOString()
}

/* ------------------------------------------------------------------ */
/* 라이프사이클                                                         */
/* ------------------------------------------------------------------ */

export type AnalysisLifecycle =
  | 'no_response'
  | 'ready_to_analyze'
  | 'draft'
  | 'reviewed'
  | 'finalized'
  | 'needs_reanalysis'

/** 프로젝트의 제출 응답 수 */
export function countSubmittedResponses(projectId: string): number {
  return surveyResponseRepository
    .search({ projectId, status: 'submitted' })
    .length
}

/** 현재 제출 응답 집합의 스냅샷 해시 */
function currentSubmittedHash(projectId: string): string {
  const ids = surveyResponseRepository
    .search({ projectId, status: 'submitted' })
    .map((r) => r.id)
  return computeSnapshotHash(ids)
}

/**
 * 확정/최신 분석이 현재 응답·인터뷰 답변보다 오래되어 재분석이 필요한지 판단한다.
 */
export function needsReanalysis(assessment: AssessmentResult): boolean {
  const currentHash = currentSubmittedHash(assessment.projectId)
  if (currentHash !== assessment.sourceSnapshotHash) return true
  // 분석 이후 새로 기록된 인터뷰 답변이 있으면 재분석 권장
  const interviews = interviewQuestionRepository.getByProjectId(
    assessment.projectId,
  )
  return interviews.some(
    (q) =>
      q.status === 'answered' &&
      q.answeredAt !== null &&
      q.answeredAt > assessment.updatedAt,
  )
}

export function getProjectAnalysisLifecycle(project: Project): AnalysisLifecycle {
  const submitted = countSubmittedResponses(project.id)
  if (submitted === 0) return 'no_response'
  const latest = assessmentRepository.getLatestByProjectId(project.id)
  if (!latest) return 'ready_to_analyze'
  if (needsReanalysis(latest)) return 'needs_reanalysis'
  if (latest.status === 'finalized') return 'finalized'
  if (latest.status === 'reviewed') return 'reviewed'
  return 'draft'
}

/* ------------------------------------------------------------------ */
/* 분석 실행 / 재분석                                                    */
/* ------------------------------------------------------------------ */

export class NoSubmittedResponseError extends Error {
  constructor() {
    super('제출 완료된 설문 응답이 없습니다.')
    this.name = 'NoSubmittedResponseError'
  }
}

/**
 * 분석을 실행하거나 갱신한다.
 * - 최신 분석이 없으면 새로 생성
 * - 최신이 draft/reviewed면 제자리 갱신(수동 보정·요약은 유지하지 않고 새로 계산)
 * - 최신이 finalized면 새 버전 draft 생성
 */
export function runOrRefreshAnalysis(projectId: string): AssessmentResult {
  const dataset = gatherAnalysisDataset(projectId)
  if (!dataset || dataset.respondents.length === 0) {
    throw new NoSubmittedResponseError()
  }
  const analyzedAt = nowIso()
  const { resultInput, issues, interviewQuestions } = runAssessmentAnalysis(
    dataset,
    analyzedAt,
  )

  const latest = assessmentRepository.getLatestByProjectId(projectId)
  let saved: AssessmentResult
  if (!latest || latest.status === 'finalized') {
    saved = assessmentRepository.create(resultInput)
  } else {
    // draft/reviewed 갱신 — 상태는 draft로 되돌림(재계산)
    saved = assessmentRepository.update(latest.id, {
      ...resultInput,
      status: 'draft',
      manualSummary: latest.manualSummary,
    })
  }

  // 자동 이슈·인터뷰 질문 교체(수동·처리된 항목 보존)
  analysisIssueRepository.replaceAutoGenerated(projectId, issues)
  interviewQuestionRepository.replaceAutoGenerated(projectId, interviewQuestions)

  activityRepository.add({
    organizationId: saved.organizationId,
    projectId,
    activityType: 'project_updated',
    title: 'AX 진단 분석이 실행되었습니다.',
    description:
      saved.analysisKind === 'website'
        ? `홈페이지 제작 준비도 ${saved.websiteReadiness?.overallScore ?? 0}점 (초안)`
        : `최종 점수 ${saved.finalScore}점 · ${RECOMMENDATION_META[saved.recommendation].label} (초안)`,
    actorName: CURRENT_USER.name,
  })

  return saved
}

/* ------------------------------------------------------------------ */
/* 총점 재계산 (수동 보정·감점 반영)                                     */
/* ------------------------------------------------------------------ */

function recomputeTotals(result: AssessmentResult): {
  subtotalScore: number
  deductionTotal: number
  finalScore: number
  recommendation: AssessmentResult['recommendation']
} {
  const measured = result.domainScores.filter((d) => d.measured)
  const measuredMax = measured.reduce((s, d) => s + d.maxScore, 0)
  const measuredRaw = measured.reduce((s, d) => s + d.rawScore, 0)
  const subtotalScore =
    measuredMax > 0
      ? Math.max(0, Math.min(100, Math.round((measuredRaw / measuredMax) * 100)))
      : 0
  const deductionTotal = result.deductions
    .filter((d) => !d.overridden)
    .reduce((s, d) => s + d.points, 0)
  const finalScore = Math.max(0, Math.min(100, subtotalScore - deductionTotal))
  // 예외 판정이 적용된 경우 유지, 아니면 점수 구간 재계산
  const recommendation =
    result.recommendationExceptionReason !== ''
      ? result.recommendation
      : recommendationForScore(finalScore)
  return { subtotalScore, deductionTotal, finalScore, recommendation }
}

export class InvalidAdjustmentError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'InvalidAdjustmentError'
  }
}

/**
 * 영역별 수동 점수 보정.
 * - 0 이상, 영역 최대점 이하
 * - 사유 필수
 * - 자동 계산값(beforeScore) 보존
 */
export function applyManualScoreAdjustment(
  assessmentId: string,
  domain: AssessmentDomain,
  afterScore: number,
  reason: string,
): AssessmentResult {
  const result = assessmentRepository.getById(assessmentId)
  if (!result) throw new InvalidAdjustmentError('분석 결과를 찾을 수 없습니다.')
  if (result.status === 'finalized') {
    throw new InvalidAdjustmentError('확정된 결과는 수정할 수 없습니다.')
  }
  if (reason.trim() === '') {
    throw new InvalidAdjustmentError('보정 사유를 입력해야 합니다.')
  }
  const target = result.domainScores.find((d) => d.domain === domain)
  if (!target) throw new InvalidAdjustmentError('영역을 찾을 수 없습니다.')
  if (afterScore < 0 || afterScore > target.maxScore) {
    throw new InvalidAdjustmentError(
      `보정 점수는 0 ~ ${target.maxScore} 범위여야 합니다.`,
    )
  }

  const beforeScore = target.rawScore
  const rounded = Math.round(afterScore * 10) / 10
  const newDomainScores = result.domainScores.map((d) =>
    d.domain === domain
      ? {
          ...d,
          rawScore: rounded,
          normalizedScore:
            d.maxScore > 0 ? Math.round((rounded / d.maxScore) * 100) : 0,
          measured: true,
        }
      : d,
  )
  const adjustment: ManualScoreAdjustment = {
    id: `adj-${domain}-${result.manualAdjustments.length + 1}`,
    domain,
    beforeScore,
    afterScore: rounded,
    reason: reason.trim(),
    actorName: CURRENT_USER.name,
    createdAt: nowIso(),
  }

  const withAdjustment: AssessmentResult = {
    ...result,
    domainScores: newDomainScores,
    manualAdjustments: [...result.manualAdjustments, adjustment],
  }
  const totals = recomputeTotals(withAdjustment)

  return assessmentRepository.update(assessmentId, {
    domainScores: newDomainScores,
    manualAdjustments: withAdjustment.manualAdjustments,
    ...totals,
  })
}

/** 자동 감점 제외/복원 (담당자 판단) */
export function toggleDeductionOverride(
  assessmentId: string,
  deductionId: string,
  overridden: boolean,
  overrideReason: string,
): AssessmentResult {
  const result = assessmentRepository.getById(assessmentId)
  if (!result) throw new InvalidAdjustmentError('분석 결과를 찾을 수 없습니다.')
  if (result.status === 'finalized') {
    throw new InvalidAdjustmentError('확정된 결과는 수정할 수 없습니다.')
  }
  if (overridden && overrideReason.trim() === '') {
    throw new InvalidAdjustmentError('감점 제외 사유를 입력해야 합니다.')
  }
  const newDeductions = result.deductions.map((d) =>
    d.id === deductionId
      ? { ...d, overridden, overrideReason: overridden ? overrideReason.trim() : '' }
      : d,
  )
  const totals = recomputeTotals({ ...result, deductions: newDeductions })
  return assessmentRepository.update(assessmentId, {
    deductions: newDeductions,
    ...totals,
  })
}

/** 담당자 최종 의견 저장 */
export function updateManualSummary(
  assessmentId: string,
  manualSummary: string,
): AssessmentResult {
  return assessmentRepository.update(assessmentId, { manualSummary })
}

/** 수동 감점 추가 */
export function addManualDeduction(
  assessmentId: string,
  points: number,
  reason: string,
): AssessmentResult {
  const result = assessmentRepository.getById(assessmentId)
  if (!result) throw new InvalidAdjustmentError('분석 결과를 찾을 수 없습니다.')
  if (points <= 0) throw new InvalidAdjustmentError('감점은 1점 이상이어야 합니다.')
  if (reason.trim() === '') throw new InvalidAdjustmentError('감점 사유를 입력해야 합니다.')
  const newDeductions = [
    ...result.deductions,
    {
      id: `ded-custom-${result.deductions.length + 1}`,
      type: 'custom' as const,
      label: DEDUCTION_TYPE_LABEL.custom,
      points: Math.round(points),
      reason: reason.trim(),
      evidenceIds: [],
      autoGenerated: false,
      overridden: false,
      overrideReason: '',
    },
  ]
  const totals = recomputeTotals({ ...result, deductions: newDeductions })
  return assessmentRepository.update(assessmentId, {
    deductions: newDeductions,
    ...totals,
  })
}

/* ------------------------------------------------------------------ */
/* 검토 / 확정 / 버전                                                    */
/* ------------------------------------------------------------------ */

export interface FinalizeCheck {
  ok: boolean
  reasons: string[]
}

/** 진단 확정 가능 여부 검증 */
export function checkCanFinalize(
  result: AssessmentResult,
  issues: AnalysisIssue[],
): FinalizeCheck {
  const reasons: string[] = []
  const criticalOpen = issues.filter(
    (i) => i.severity === 'critical' && i.status === 'open',
  )
  if (criticalOpen.length > 0) {
    reasons.push(`중대 이슈 ${criticalOpen.length}건을 확인 또는 해결해야 합니다.`)
  }
  if (result.manualSummary.trim() === '') {
    reasons.push('내부 최종 의견을 작성해야 합니다.')
  }
  if (result.suggestedNextActions.length === 0) {
    reasons.push('다음 행동이 1개 이상 필요합니다.')
  }
  return { ok: reasons.length === 0, reasons }
}

export function markAssessmentReviewed(assessmentId: string): AssessmentResult {
  return assessmentRepository.markReviewed(assessmentId, CURRENT_USER.name)
}

export class FinalizeBlockedError extends Error {
  constructor(reasons: string[]) {
    super(reasons.join(' '))
    this.name = 'FinalizeBlockedError'
  }
}

export function finalizeAssessment(assessmentId: string): AssessmentResult {
  const result = assessmentRepository.getById(assessmentId)
  if (!result) throw new FinalizeBlockedError(['분석 결과를 찾을 수 없습니다.'])
  const issues = analysisIssueRepository.getByProjectId(result.projectId)
  const check = checkCanFinalize(result, issues)
  if (!check.ok) throw new FinalizeBlockedError(check.reasons)

  const finalized = assessmentRepository.finalize(assessmentId, CURRENT_USER.name)

  const project = projectRepository.getById(result.projectId)
  activityRepository.add({
    organizationId: result.organizationId,
    projectId: result.projectId,
    activityType: 'status_changed',
    title: 'AX 진단 결과가 확정되었습니다.',
    description:
      finalized.analysisKind === 'website'
        ? `홈페이지 제작 준비도 ${finalized.websiteReadiness?.overallScore ?? 0}점`
        : `최종 점수 ${finalized.finalScore}점, 판정: ${RECOMMENDATION_META[finalized.recommendation].label}${project ? '' : ''}`,
    actorName: CURRENT_USER.name,
  })

  return finalized
}

/** 새 버전 분석 생성 (확정 결과가 있을 때) */
export function createNewAnalysisVersion(projectId: string): AssessmentResult {
  return runOrRefreshAnalysis(projectId)
}

/* ------------------------------------------------------------------ */
/* 이슈 / 인터뷰 액션 래퍼                                               */
/* ------------------------------------------------------------------ */

export function acknowledgeIssue(issueId: string): AnalysisIssue {
  return analysisIssueRepository.update(issueId, { status: 'acknowledged' })
}

export function resolveIssue(issueId: string, note: string): AnalysisIssue {
  return analysisIssueRepository.resolve(issueId, note)
}

export function excludeIssue(issueId: string, reason: string): AnalysisIssue {
  return analysisIssueRepository.exclude(issueId, reason)
}

export function reopenIssue(issueId: string): AnalysisIssue {
  return analysisIssueRepository.update(issueId, {
    status: 'open',
    resolutionNote: '',
    resolvedAt: null,
  })
}

export function addManualIssue(
  projectId: string,
  title: string,
  description: string,
): AnalysisIssue {
  return analysisIssueRepository.createMany([
    {
      projectId,
      type: 'missing_data',
      severity: 'info',
      title,
      description,
      relatedQuestionIds: [],
      relatedResponseIds: [],
      evidenceIds: [],
      suggestedAction: '',
      status: 'open',
      resolutionNote: '',
      resolvedAt: null,
      ruleKey: `manual-${Date.now()}`,
      autoGenerated: false,
    },
  ])[0]
}

export function selectInterviewQuestion(id: string): InterviewQuestion {
  return interviewQuestionRepository.select(id)
}

export function excludeInterviewQuestion(id: string): InterviewQuestion {
  return interviewQuestionRepository.exclude(id)
}

export function recordInterviewAnswer(
  id: string,
  answer: string,
): InterviewQuestion {
  return interviewQuestionRepository.answer(id, answer)
}

export function addManualInterviewQuestion(
  projectId: string,
  question: string,
  targetRole: InterviewQuestion['targetRespondentRole'],
): InterviewQuestion {
  return interviewQuestionRepository.create({
    projectId,
    sourceIssueIds: [],
    targetRespondentRole: targetRole,
    priority: 'medium',
    question,
    reason: '담당자가 직접 추가한 질문입니다.',
    expectedEvidence: '',
    status: 'selected',
    manual: true,
    answer: '',
    answeredAt: null,
    ruleKey: `manual-${Date.now()}`,
  })
}

/* ------------------------------------------------------------------ */
/* 조회 헬퍼                                                            */
/* ------------------------------------------------------------------ */

export interface ProjectAnalysisContext {
  project: Project
  latest: AssessmentResult | null
  issues: AnalysisIssue[]
  interviews: InterviewQuestion[]
  submittedCount: number
  lifecycle: AnalysisLifecycle
  needsReanalysisFlag: boolean
}

export function getProjectAnalysisContext(
  projectId: string,
): ProjectAnalysisContext | null {
  const project = projectRepository.getById(projectId)
  if (!project) return null
  const latest = assessmentRepository.getLatestByProjectId(projectId)
  return {
    project,
    latest,
    issues: analysisIssueRepository.getByProjectId(projectId),
    interviews: interviewQuestionRepository.getByProjectId(projectId),
    submittedCount: countSubmittedResponses(projectId),
    lifecycle: getProjectAnalysisLifecycle(project),
    needsReanalysisFlag: latest ? needsReanalysis(latest) : false,
  }
}
