import { useEffect, useState } from 'react'
import { Archive, Ban, MinusCircle, Pencil, Star } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import type {
  AutomationCandidate,
  CandidateDomainScore,
  CandidateRiskDeduction,
} from '../../types/selection'
import { automationCandidateRepository } from '../../repositories'
import { useStoreVersion } from '../../lib/useStoreVersion'
import { RESPONDENT_ROLE_META } from '../../lib/surveyMeta'
import { MVP_TEMPLATE_META } from '../../lib/selectionMeta'
import { mvpLevelLabel } from '../../lib/domainMeta'
import { Button } from '../../components/ui/Button'
import { DetailHeader } from '../../components/ui/DetailHeader'
import { DropdownMenu } from '../../components/ui/DropdownMenu'
import { Modal } from '../../components/ui/Modal'
import { NotFoundState } from '../../components/ui/NotFoundState'
import { Panel } from '../../components/ui/Panel'
import { useToast } from '../../components/ui/toastContext'
import {
  adjustCandidateDomainScore,
  archiveCandidate,
  setCandidateStatus,
  toggleCandidateDeduction,
  updateCandidate,
} from '../../services/selectionService'
import {
  AiNecessityBadge,
  AutomationApproachBadge,
  CandidateConfidenceBadge,
  CandidateStatusBadge,
  ComplexityBadge,
  PriorityQuadrantBadge,
  TaskFamilyBadge,
} from '../../components/selection/badges'
import {
  CandidateDependencyList,
  CandidateDomainScoreList,
  CandidateMetricList,
  CandidateRiskDeductionList,
  ExpectedEffectList,
} from '../../components/selection/candidateDetailParts'
import { CandidateScoreAdjustModal } from '../../components/selection/candidateModals'

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt className="text-[0.875rem] text-slate-400">{label}</dt>
      <dd className="mt-0.5 text-[13px] break-keep whitespace-pre-wrap text-slate-700">{value || '-'}</dd>
    </div>
  )
}

export function CandidateDetailPage() {
  const { projectId = '', candidateId = '' } = useParams()
  const navigate = useNavigate()
  const { showToast } = useToast()
  const version = useStoreVersion()
  const [adjustDomain, setAdjustDomain] = useState<CandidateDomainScore | null>(null)
  const [excludeDeduction, setExcludeDeduction] = useState<CandidateRiskDeduction | null>(null)
  const [excludeReason, setExcludeReason] = useState('')
  const [editOpen, setEditOpen] = useState(false)

  const candidate = ((): AutomationCandidate | null => {
    void version
    return automationCandidateRepository.getById(candidateId)
  })()

  if (!candidate || candidate.projectId !== projectId) {
    return (
      <NotFoundState
        title="후보를 찾을 수 없습니다"
        description="주소가 잘못되었거나 이미 삭제·병합된 후보입니다."
        backTo={`/selection/projects/${projectId}/candidates`}
        backLabel="후보 보드로"
      />
    )
  }

  const handleAdjust = (afterScore: number, reason: string) => {
    try {
      adjustCandidateDomainScore(candidate.id, adjustDomain!.domain, afterScore, reason)
      showToast('점수를 보정했습니다.')
      setAdjustDomain(null)
    } catch (error) {
      showToast(error instanceof Error ? error.message : '보정에 실패했습니다.')
    }
  }

  const handleToggleDeduction = (d: CandidateRiskDeduction) => {
    if (d.excluded) {
      toggleCandidateDeduction(candidate.id, d.id, false, '')
      showToast('감점을 복원했습니다.')
      return
    }
    setExcludeReason('')
    setExcludeDeduction(d)
  }

  const submitExclude = () => {
    try {
      toggleCandidateDeduction(candidate.id, excludeDeduction!.id, true, excludeReason)
      showToast('감점을 제외했습니다.')
      setExcludeDeduction(null)
    } catch (error) {
      showToast(error instanceof Error ? error.message : '처리에 실패했습니다.')
    }
  }

  return (
    <div className="flex flex-col gap-5">
      <DetailHeader
        backTo={`/selection/projects/${projectId}/candidates`}
        backLabel="후보 보드로"
        title={candidate.name}
        badges={
          <>
            <CandidateStatusBadge status={candidate.status} />
            <span className="rounded-md border border-slate-200 bg-slate-50 px-2 py-0.5 text-[0.875rem] font-semibold text-slate-500">
              {candidate.priorityScore}점
            </span>
            <PriorityQuadrantBadge quadrant={candidate.quadrant} />
            <CandidateConfidenceBadge confidence={candidate.confidence} />
            {!candidate.autoGenerated && (
              <span className="rounded-md border border-accent-200 bg-accent-50 px-2 py-0.5 text-[0.875rem] font-medium text-accent-700">수동</span>
            )}
          </>
        }
        meta={<><span>{candidate.confidenceReason}</span></>}
        actions={
          <>
            <Button variant="secondary" onClick={() => setEditOpen(true)}>
              <Pencil aria-hidden="true" className="size-4" />
              편집
            </Button>
            <Button variant="primary" onClick={() => { setCandidateStatus(candidate.id, 'shortlisted'); showToast('우선 후보로 지정했습니다.') }}>
              <Star aria-hidden="true" className="size-4" />
              우선 후보 지정
            </Button>
            <DropdownMenu
              ariaLabel="후보 작업"
              items={[
                { key: 'defer', label: '보류 처리', icon: MinusCircle, onSelect: () => { setCandidateStatus(candidate.id, 'deferred'); showToast('보류 처리했습니다.') } },
                { key: 'reject', label: '제외 처리', icon: Ban, danger: true, onSelect: () => { setCandidateStatus(candidate.id, 'rejected'); showToast('제외 처리했습니다.') } },
                { key: 'archive', label: '보관', icon: Archive, onSelect: () => { archiveCandidate(candidate.id); showToast('보관 처리했습니다.'); navigate(`/selection/projects/${projectId}/candidates`) } },
              ]}
            />
          </>
        }
      />

      {candidate.quadrantExceptionReason && (
        <p className="rounded-(--radius-card) border border-warning-200 bg-warning-50/60 px-4 py-2.5 text-[13px] break-keep text-warning-800">
          분류 예외: {candidate.quadrantExceptionReason}
        </p>
      )}

      <div className="grid grid-cols-1 gap-5 xl:grid-cols-3">
        <div className="flex min-w-0 flex-col gap-5 xl:col-span-2">
          <Panel title="문제와 목표">
            <dl className="flex flex-col gap-3">
              <Row label="문제 정의" value={candidate.problemStatement} />
              <Row label="영향받는 사용자" value={candidate.users} />
              <Row label="자동화 후 목표 흐름" value={candidate.desiredProcess} />
              <Row label="제외 범위" value={candidate.excludedScope} />
            </dl>
          </Panel>

          <Panel title="현재 업무 흐름">
            <dl className="grid grid-cols-1 gap-3 sm:grid-cols-2">
              <Row label="시작 조건" value={candidate.startCondition} />
              <Row label="종료 조건" value={candidate.endCondition} />
              <Row label="담당자" value={candidate.users} />
              <Row label="담당 역할" value={candidate.ownerRole === 'unknown' ? '미상' : RESPONDENT_ROLE_META[candidate.ownerRole].label} />
              <Row label="입력 데이터" value={candidate.inputData} />
              <Row label="출력 결과물" value={candidate.outputResult} />
              <Row label="현재 처리 흐름" value={candidate.currentProcess} />
            </dl>
          </Panel>

          <Panel title="업무량 지표">
            <CandidateMetricList metrics={candidate.metrics} />
          </Panel>

          <Panel title="예상 효과">
            <ExpectedEffectList effects={candidate.expectedEffects} />
          </Panel>

          <Panel title="점수 상세">
            <p className="mb-3 rounded-(--radius-control) border border-slate-200 bg-slate-50 px-3 py-2 text-[0.875rem] break-keep text-slate-500">
              제출 응답과 사전 정의된 선별 규칙을 기준으로 계산되었습니다. 영역 점수는 담당자가 보정할 수 있으며 자동 계산값이 함께 보존됩니다.
            </p>
            <CandidateDomainScoreList domainScores={candidate.domainScores} editable onAdjust={setAdjustDomain} />
          </Panel>

          <Panel title="위험 감점">
            <CandidateRiskDeductionList deductions={candidate.deductions} editable onToggle={handleToggleDeduction} />
          </Panel>
        </div>

        <div className="flex min-w-0 flex-col gap-5">
          <Panel title="추천 자동화 방식">
            <div className="flex flex-col gap-2">
              <AutomationApproachBadge approach={candidate.automationApproach} />
              <p className="text-[13px] break-keep text-slate-600">{candidate.automationApproachReason}</p>
              <ComplexityBadge complexity={candidate.complexity} />
            </div>
          </Panel>

          <Panel title="AI 필요성">
            <div className="flex flex-col gap-2">
              <AiNecessityBadge necessity={candidate.aiNecessity} />
              <p className="text-[13px] break-keep text-slate-600">{candidate.aiReason}</p>
              {candidate.humanReviewRequired && (
                <p className="text-[0.875rem] text-warning-700">결과에 대한 담당자 최종 검토가 필요합니다.</p>
              )}
            </div>
          </Panel>

          <Panel title="선행조건·의존성">
            <CandidateDependencyList dependencies={candidate.dependencies} />
          </Panel>

          <Panel title="추천 MVP 템플릿">
            <ul className="flex flex-col gap-2">
              {candidate.templateMix.map((t) => (
                <li key={t.template} className="flex items-center justify-between gap-2 rounded-(--radius-control) border border-slate-200 px-3 py-2">
                  <div className="min-w-0">
                    <p className="text-[13px] font-medium text-slate-700">{MVP_TEMPLATE_META[t.template].label}</p>
                    <p className="text-[0.875rem] text-slate-400">{t.reason}</p>
                  </div>
                  <span className="shrink-0 text-sm font-bold text-slate-800">{t.percentage}%</span>
                </li>
              ))}
            </ul>
            <p className="mt-2 text-[0.875rem] text-slate-400">
              권장 MVP 수준: {mvpLevelLabel(candidate.recommendedMvpLevel, candidate.taskFamily === 'website_content' ? 'website' : 'ax')}
            </p>
          </Panel>

          <Panel title="원본 근거">
            <div className="flex flex-col gap-1.5 text-[13px] text-slate-600">
              <p>업무군: <TaskFamilyBadge family={candidate.taskFamily} /></p>
              <p>출처 질문: {candidate.sourceQuestionCodes.join(', ') || '-'}</p>
              <p>진단 근거 {candidate.sourceEvidenceIds.length}건 · 출처 유형 {candidate.sourceTypes.length}종</p>
              {candidate.mergedFromIds.length > 0 && <p className="text-[0.875rem] text-slate-400">병합된 후보 {candidate.mergedFromIds.length}건 포함</p>}
            </div>
          </Panel>
        </div>
      </div>

      <CandidateScoreAdjustModal
        open={adjustDomain !== null}
        domainScore={adjustDomain}
        onClose={() => setAdjustDomain(null)}
        onSubmit={handleAdjust}
      />

      <Modal
        open={excludeDeduction !== null}
        title="감점 제외"
        onClose={() => setExcludeDeduction(null)}
        footer={
          <>
            <Button variant="secondary" onClick={() => setExcludeDeduction(null)}>취소</Button>
            <Button variant="primary" onClick={submitExclude}>제외</Button>
          </>
        }
      >
        <label htmlFor="cand-exclude-reason" className="mb-1.5 block text-sm font-medium text-slate-700">제외 사유</label>
        <textarea
          id="cand-exclude-reason"
          value={excludeReason}
          onChange={(e) => setExcludeReason(e.target.value)}
          rows={3}
          className="w-full resize-none rounded-(--radius-control) border border-slate-300 px-3 py-2 text-sm focus:border-brand-500 focus:outline-none focus:ring-2 focus:ring-brand-100"
        />
      </Modal>

      <CandidateEditModal open={editOpen} candidate={candidate} onClose={() => setEditOpen(false)} onSaved={() => { setEditOpen(false); showToast('후보를 수정했습니다.') }} />
    </div>
  )
}

/* 후보 편집 모달 */
function CandidateEditModal({
  open,
  candidate,
  onClose,
  onSaved,
}: {
  open: boolean
  candidate: AutomationCandidate
  onClose: () => void
  onSaved: () => void
}) {
  const [form, setForm] = useState({
    name: candidate.name,
    problemStatement: candidate.problemStatement,
    currentProcess: candidate.currentProcess,
    users: candidate.users,
    inputData: candidate.inputData,
    outputResult: candidate.outputResult,
    desiredProcess: candidate.desiredProcess,
    excludedScope: candidate.excludedScope,
    manualNotes: candidate.manualNotes,
  })
  useEffect(() => {
    if (open) {
      setForm({
        name: candidate.name,
        problemStatement: candidate.problemStatement,
        currentProcess: candidate.currentProcess,
        users: candidate.users,
        inputData: candidate.inputData,
        outputResult: candidate.outputResult,
        desiredProcess: candidate.desiredProcess,
        excludedScope: candidate.excludedScope,
        manualNotes: candidate.manualNotes,
      })
    }
  }, [open, candidate])

  const cls = 'w-full rounded-(--radius-control) border border-slate-300 px-3 py-2 text-sm focus:border-brand-500 focus:outline-none focus:ring-2 focus:ring-brand-100'
  const save = () => {
    updateCandidate(candidate.id, { ...form, name: form.name.trim() || candidate.name, nameNeedsReview: false })
    onSaved()
  }
  return (
    <Modal
      open={open}
      title="후보 편집"
      onClose={onClose}
      size="lg"
      footer={
        <>
          <Button variant="secondary" onClick={onClose}>취소</Button>
          <Button variant="primary" onClick={save}>저장</Button>
        </>
      }
    >
      <div className="flex flex-col gap-3">
        {([
          ['name', '후보명', false],
          ['problemStatement', '문제 정의', true],
          ['currentProcess', '현재 업무 흐름', true],
          ['desiredProcess', '자동화 후 목표 흐름', true],
          ['users', '담당자/사용자', false],
          ['inputData', '입력 데이터', false],
          ['outputResult', '출력 결과물', false],
          ['excludedScope', '제외 범위', true],
          ['manualNotes', '내부 메모', true],
        ] as const).map(([key, label, multiline]) => (
          <div key={key}>
            <label className="mb-1 block text-sm font-medium text-slate-700">{label}</label>
            {multiline ? (
              <textarea value={form[key]} onChange={(e) => setForm((f) => ({ ...f, [key]: e.target.value }))} rows={2} className={cls} />
            ) : (
              <input value={form[key]} onChange={(e) => setForm((f) => ({ ...f, [key]: e.target.value }))} className={cls} />
            )}
          </div>
        ))}
        <p className="text-[0.875rem] break-keep text-slate-400">
          자동 추출 원본 점수·근거는 보존되며, 편집한 내용은 수동 수정으로 표시됩니다.
        </p>
      </div>
    </Modal>
  )
}
