import { Pencil, RotateCcw, TriangleAlert } from 'lucide-react'
import type {
  CandidateDependency,
  CandidateDomainScore,
  CandidateMetric,
  CandidateRiskDeduction,
  ExpectedEffect,
} from '../../types/selection'
import { CANDIDATE_SCORE_DOMAIN_META, DEPENDENCY_TYPE_META } from '../../lib/selectionMeta'
import { effectText, metricText } from '../../lib/selectionFormat'
import { ScoreBar } from '../assessment/scoreParts'
import { CandidateConfidenceBadge } from './badges'

/* 영역별 점수 */
export function CandidateDomainScoreList({
  domainScores,
  editable,
  onAdjust,
}: {
  domainScores: CandidateDomainScore[]
  editable?: boolean
  onAdjust?: (d: CandidateDomainScore) => void
}) {
  if (domainScores.length === 0) {
    return <p className="text-[13px] text-slate-500">점수가 계산되지 않은 후보입니다.</p>
  }
  return (
    <div className="flex flex-col gap-2.5">
      {domainScores.map((d) => {
        const value = d.adjustedScore ?? d.rawScore
        const tone = d.normalizedScore >= 66 ? 'success' : d.normalizedScore >= 40 ? 'info' : 'warning'
        return (
          <div key={d.domain} className="rounded-(--radius-card) border border-slate-200 px-3.5 py-2.5">
            <div className="flex flex-col gap-2 sm:flex-row sm:items-center">
              <div className="flex min-w-0 flex-1 items-center gap-2">
                <span className="text-[13px] font-medium text-slate-700">
                  {CANDIDATE_SCORE_DOMAIN_META[d.domain].label}
                </span>
                {d.adjustedScore !== null && (
                  <span className="rounded-md border border-accent-200 bg-accent-50 px-1.5 py-0.5 text-[0.8125rem] font-medium text-accent-700">
                    보정됨
                  </span>
                )}
              </div>
              <div className="flex items-center gap-2 sm:w-56">
                <div className="min-w-0 flex-1">
                  <ScoreBar normalized={d.normalizedScore} tone={tone} label={CANDIDATE_SCORE_DOMAIN_META[d.domain].label} />
                </div>
                <span className="w-16 shrink-0 text-right text-sm font-semibold text-slate-800">
                  {value}
                  <span className="text-[0.875rem] font-normal text-slate-400"> / {d.maxScore}</span>
                </span>
                {editable && onAdjust && (
                  <button
                    type="button"
                    onClick={() => onAdjust(d)}
                    aria-label={`${CANDIDATE_SCORE_DOMAIN_META[d.domain].label} 점수 보정`}
                    className="flex size-7 cursor-pointer items-center justify-center rounded-lg text-slate-400 hover:bg-slate-100 hover:text-slate-600"
                  >
                    <Pencil aria-hidden="true" className="size-3.5" />
                  </button>
                )}
              </div>
            </div>
            {d.adjustedScore !== null && d.adjustmentReason && (
              <p className="mt-1.5 text-[0.875rem] break-keep text-accent-700">
                보정: 자동 {d.autoScore}점 → {d.adjustedScore}점 · {d.adjustmentReason}
              </p>
            )}
            {d.warnings.map((w) => (
              <p key={w} className="mt-1 flex items-start gap-1 text-[0.875rem] break-keep text-warning-700">
                <TriangleAlert aria-hidden="true" className="mt-0.5 size-3 shrink-0" />
                {w}
              </p>
            ))}
          </div>
        )
      })}
    </div>
  )
}

/* 위험 감점 */
export function CandidateRiskDeductionList({
  deductions,
  editable,
  onToggle,
}: {
  deductions: CandidateRiskDeduction[]
  editable?: boolean
  onToggle?: (d: CandidateRiskDeduction) => void
}) {
  if (deductions.length === 0) {
    return <p className="text-[13px] text-slate-500">적용된 위험 감점이 없습니다.</p>
  }
  return (
    <ul className="flex flex-col gap-2">
      {deductions.map((d) => (
        <li
          key={d.id}
          className={`rounded-(--radius-card) border px-3.5 py-2.5 ${d.excluded ? 'border-slate-200 bg-slate-50' : 'border-danger-200 bg-danger-50/40'}`}
        >
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-[13px] font-medium text-slate-800">{d.label}</span>
            <span className={`text-sm font-bold ${d.excluded ? 'text-slate-400 line-through' : 'text-danger-600'}`}>
              -{d.points}점
            </span>
            {!d.autoGenerated && (
              <span className="rounded-md border border-accent-200 bg-accent-50 px-1.5 py-0.5 text-[0.8125rem] font-medium text-accent-700">수동</span>
            )}
            {editable && onToggle && (
              <button
                type="button"
                onClick={() => onToggle(d)}
                className="ml-auto inline-flex cursor-pointer items-center gap-1 text-[13px] font-medium text-brand-600 hover:text-brand-700"
              >
                {d.excluded ? (
                  <>
                    <RotateCcw aria-hidden="true" className="size-3.5" />
                    복원
                  </>
                ) : (
                  '제외'
                )}
              </button>
            )}
          </div>
          <p className="mt-1 text-[0.875rem] break-keep text-slate-600">{d.reason}</p>
          {d.resolution && <p className="mt-0.5 text-[0.875rem] break-keep text-brand-700">해결: {d.resolution}</p>}
          {d.excluded && d.exclusionReason && (
            <p className="mt-0.5 text-[0.875rem] break-keep text-slate-500">제외 사유: {d.exclusionReason}</p>
          )}
        </li>
      ))}
    </ul>
  )
}

/* 예상 효과 */
export function ExpectedEffectList({ effects }: { effects: ExpectedEffect[] }) {
  if (effects.length === 0) return <p className="text-[13px] text-slate-500">예상 효과가 정리되지 않았습니다.</p>
  return (
    <ul className="flex flex-col gap-2">
      {effects.map((e) => (
        <li key={e.id} className="rounded-(--radius-card) border border-slate-200 px-3.5 py-2.5">
          <div className="flex items-center justify-between gap-2">
            <span className="text-[13px] font-medium text-slate-800">{effectText(e)}</span>
            {e.notEstimable ? (
              <span className="shrink-0 rounded-md border border-warning-200 bg-warning-50 px-1.5 py-0.5 text-[0.8125rem] font-medium text-warning-700">
                산정 필요
              </span>
            ) : (
              <CandidateConfidenceBadge confidence={e.confidence} />
            )}
          </div>
          {e.calculationMethod && <p className="mt-1 text-[0.875rem] text-slate-500">계산식: {e.calculationMethod}</p>}
          {e.assumption && <p className="mt-0.5 text-[0.875rem] break-keep text-slate-400">{e.assumption}</p>}
        </li>
      ))}
    </ul>
  )
}

/* 지표 */
export function CandidateMetricList({ metrics }: { metrics: CandidateMetric[] }) {
  if (metrics.length === 0) return <p className="text-[13px] text-slate-500">확인된 업무량 지표가 없습니다.</p>
  return (
    <ul className="flex flex-wrap gap-2">
      {metrics.map((m) => (
        <li key={m.id} className="rounded-(--radius-control) border border-slate-200 bg-slate-50 px-3 py-1.5 text-[13px] text-slate-700">
          {metricText(m)}
          {m.manuallyEdited && <span className="ml-1 text-[0.8125rem] text-accent-600">(수정됨)</span>}
        </li>
      ))}
    </ul>
  )
}

/* 선행조건·의존성 */
export function CandidateDependencyList({ dependencies }: { dependencies: CandidateDependency[] }) {
  if (dependencies.length === 0) return <p className="text-[13px] text-slate-500">식별된 선행조건이 없습니다.</p>
  return (
    <ul className="flex flex-col gap-2">
      {dependencies.map((d) => {
        const meta = DEPENDENCY_TYPE_META[d.type]
        return (
          <li key={d.id} className="flex items-start gap-2.5 rounded-(--radius-card) border border-slate-200 px-3.5 py-2.5">
            <meta.icon aria-hidden="true" className="mt-0.5 size-4 shrink-0 text-slate-400" />
            <div className="min-w-0">
              <p className="text-[13px] font-medium text-slate-700">
                {d.title}
                {d.requiredBeforeMvp && (
                  <span className="ml-1.5 rounded-md border border-warning-200 bg-warning-50 px-1.5 py-0.5 text-[0.8125rem] font-medium text-warning-700">
                    MVP 전 필수
                  </span>
                )}
              </p>
              <p className="mt-0.5 text-[0.875rem] break-keep text-slate-500">{d.description}</p>
            </div>
          </li>
        )
      })}
    </ul>
  )
}
