import type { RespondentRole } from './index'

/* ------------------------------------------------------------------ */
/* 진단 분석 도메인 타입 (Stage 5)                                       */
/*                                                                     */
/* 규칙 기반 진단 분석·AX 적합성 점수 산정 도메인.                        */
/* 모든 점수는 제출 응답과 사전 정의된 규칙으로 계산되며,                 */
/* 자동 계산값과 담당자 수동 보정값을 함께 보존한다.                     */
/* ------------------------------------------------------------------ */

/** 분석 결과 상태 */
export type AssessmentStatus = 'draft' | 'reviewed' | 'finalized' | 'superseded'

/** 최종 판정 (AX 프로젝트) */
export type AssessmentRecommendation =
  | 'ax_strongly_recommended'
  | 'simple_automation_recommended'
  | 'diagnosis_document_first'
  | 'funding_consulting_first'
  | 'build_deferred_data'
  | 'build_deferred_adoption'
  | 'expert_review_required'

/** AX 적합성 점수 영역 (결과에 쓰는 7개 영역) */
export type AssessmentDomain =
  | 'repetition'
  | 'economic'
  | 'data_readiness'
  | 'process_clarity'
  | 'adoption'
  | 'execution'
  | 'funding_connection'

/** 신뢰도 3단계 (영역 단위) */
export type ScoreConfidence = 'high' | 'medium' | 'low'

/** 분석 전체 신뢰도 (insufficient 포함) */
export type AssessmentConfidence = 'high' | 'medium' | 'low' | 'insufficient'

export interface DomainScore {
  domain: AssessmentDomain
  /** 원점수(영역 배점 환산) */
  rawScore: number
  /** 영역 최대 배점 */
  maxScore: number
  /** 0~100 정규화 점수 */
  normalizedScore: number
  evidenceCount: number
  /** 이 영역에 해당하는 점수 대상 문항 수(스냅샷 합집합) */
  applicableQuestionCount: number
  /** 실제 점수화된(응답된) 문항 수 */
  answeredQuestionCount: number
  confidence: ScoreConfidence
  evidenceIds: string[]
  explanation: string
  warnings: string[]
  /** 응답이 하나도 없어 점수 계산에서 제외된 영역 */
  measured: boolean
}

/* ------------------------------------------------------------------ */
/* 감점                                                                 */
/* ------------------------------------------------------------------ */

export type AssessmentDeductionType =
  | 'no_owner'
  | 'no_field_participant'
  | 'insufficient_data'
  | 'inconsistent_process'
  | 'high_privacy_risk'
  | 'expert_judgment_dominant'
  | 'no_measurable_kpi'
  | 'low_adoption_will'
  | 'formal_build_only'
  | 'severe_response_conflict'
  | 'custom'

export interface AssessmentDeduction {
  id: string
  type: AssessmentDeductionType
  label: string
  /** 양수로 저장하고 총점에서 차감한다 */
  points: number
  reason: string
  evidenceIds: string[]
  autoGenerated: boolean
  overridden: boolean
  overrideReason: string
}

/* ------------------------------------------------------------------ */
/* 근거(Evidence)                                                       */
/* ------------------------------------------------------------------ */

export type AssessmentEvidenceType =
  | 'answer'
  | 'calculated_metric'
  | 'conflict'
  | 'missing_data'
  | 'risk_signal'
  | 'manual_note'

export interface AssessmentEvidence {
  id: string
  projectId: string
  distributionId: string
  responseId: string
  respondentRole: RespondentRole
  respondentName: string
  questionId: string
  questionCode: string
  questionText: string
  category: string
  scoringDomain: string
  /** 사람이 읽을 수 있는 답변 표현 */
  answerValue: string
  /** 0~100 정규화 값 (점수화되지 않으면 null) */
  normalizedValue: number | null
  evidenceType: AssessmentEvidenceType
  weight: number
  /** 영역 점수 기여도(0~100 정규화 값에 가중치 반영한 표시용) */
  contribution: number
  explanation: string
  createdAt: string
}

/* ------------------------------------------------------------------ */
/* 응답자 비교                                                          */
/* ------------------------------------------------------------------ */

export type ResponseComparisonStatus =
  | 'aligned'
  | 'minor_gap'
  | 'major_gap'
  | 'insufficient'

export type ComparisonImportance = 'low' | 'medium' | 'high' | 'critical'

export interface ComparisonRespondentValue {
  role: RespondentRole
  respondentName: string
  displayValue: string
  normalizedValue: number | null
  responseId: string
}

export interface ResponseComparisonItem {
  id: string
  topicKey: string
  title: string
  description: string
  category: string
  relatedQuestionCodes: string[]
  respondentValues: ComparisonRespondentValue[]
  status: ResponseComparisonStatus
  /** 0~100, 차이가 클수록 큼 */
  gapScore: number
  importance: ComparisonImportance
  interpretation: string
  requiresInterview: boolean
  evidenceIds: string[]
}

/* ------------------------------------------------------------------ */
/* 이슈(모순·누락·위험)                                                  */
/* ------------------------------------------------------------------ */

export type AnalysisIssueType =
  | 'missing_data'
  | 'contradiction'
  | 'perception_gap'
  | 'risk_signal'
  | 'invalid_answer'
  | 'insufficient_response'
  | 'expert_review'
  | 'outlier'

export type AnalysisIssueSeverity = 'info' | 'warning' | 'critical'

export type AnalysisIssueStatus = 'open' | 'acknowledged' | 'resolved' | 'excluded'

export interface AnalysisIssue {
  id: string
  projectId: string
  type: AnalysisIssueType
  severity: AnalysisIssueSeverity
  title: string
  description: string
  relatedQuestionIds: string[]
  relatedResponseIds: string[]
  evidenceIds: string[]
  suggestedAction: string
  status: AnalysisIssueStatus
  resolutionNote: string
  resolvedAt: string | null
  /** 자동 생성 규칙 키 (재분석 시 자동 이슈 교체용) */
  ruleKey: string
  autoGenerated: boolean
  createdAt: string
  updatedAt: string
}

export type AnalysisIssueInput = Omit<
  AnalysisIssue,
  'id' | 'createdAt' | 'updatedAt'
>

/* ------------------------------------------------------------------ */
/* 추가 인터뷰 질문                                                      */
/* ------------------------------------------------------------------ */

export type InterviewQuestionPriority = 'low' | 'medium' | 'high' | 'critical'

export type InterviewQuestionStatus =
  | 'suggested'
  | 'selected'
  | 'answered'
  | 'excluded'

export interface InterviewQuestion {
  id: string
  projectId: string
  sourceIssueIds: string[]
  targetRespondentRole: RespondentRole
  priority: InterviewQuestionPriority
  question: string
  reason: string
  expectedEvidence: string
  status: InterviewQuestionStatus
  manual: boolean
  answer: string
  answeredAt: string | null
  /** 자동 생성 규칙 키 (재생성 시 교체용) */
  ruleKey: string
  createdAt: string
  updatedAt: string
}

export type InterviewQuestionInput = Omit<
  InterviewQuestion,
  'id' | 'createdAt' | 'updatedAt'
>

/* ------------------------------------------------------------------ */
/* 수동 점수 보정                                                        */
/* ------------------------------------------------------------------ */

export interface ManualScoreAdjustment {
  id: string
  domain: AssessmentDomain
  beforeScore: number
  afterScore: number
  reason: string
  actorName: string
  createdAt: string
}

/* ------------------------------------------------------------------ */
/* 홈페이지 제작 준비도                                                  */
/* ------------------------------------------------------------------ */

export type WebsiteReadinessDomain =
  | 'purpose_clarity'
  | 'customer_clarity'
  | 'content_readiness'
  | 'brand_direction'
  | 'asset_readiness'
  | 'operation_readiness'

export type WebsiteReadinessRecommendation =
  | 'design_ready'
  | 'content_supplement'
  | 'structure_first'
  | 'planning_interview_first'

export interface WebsiteReadinessScore {
  domain: WebsiteReadinessDomain
  score: number
  maxScore: number
  confidence: ScoreConfidence
  evidenceIds: string[]
  explanation: string
}

export interface WebsiteReadinessResult {
  overallScore: number
  recommendation: WebsiteReadinessRecommendation
  confidence: AssessmentConfidence
  domains: WebsiteReadinessScore[]
  missingAssets: string[]
  missingContent: string[]
  designRisks: string[]
  nextActions: string[]
}

/* ------------------------------------------------------------------ */
/* 분석 결과 (AssessmentResult)                                          */
/* ------------------------------------------------------------------ */

export interface AssessmentResult {
  id: string
  projectId: string
  organizationId: string
  version: number
  status: AssessmentStatus
  /** 분석 대상 유형 */
  analysisKind: 'ax' | 'website' | 'ax_website'
  sourceResponseIds: string[]
  sourceDistributionIds: string[]
  /** 사용한 응답 스냅샷 해시 (재분석 필요 판정용) */
  sourceSnapshotHash: string

  domainScores: DomainScore[]
  /** 점수 근거 (계산 시점 동결) */
  evidence: AssessmentEvidence[]
  /** 응답자 비교 (계산 시점 동결) */
  comparisons: ResponseComparisonItem[]
  subtotalScore: number
  deductions: AssessmentDeduction[]
  deductionTotal: number
  finalScore: number
  recommendation: AssessmentRecommendation
  /** 점수 구간에 따른 기본 판정 (예외 적용 전) */
  baseRecommendation: AssessmentRecommendation
  /** 예외 판정이 적용된 이유 (없으면 빈 문자열) */
  recommendationExceptionReason: string
  confidence: AssessmentConfidence
  confidenceReason: string
  dataCompleteness: number
  respondentCoverage: number
  scoreCoverage: number

  keyStrengths: string[]
  keyWeaknesses: string[]
  keyRisks: string[]
  missingDataSummary: string[]
  conflictSummary: string[]
  suggestedNextActions: string[]

  autoSummary: string
  manualSummary: string
  manualAdjustments: ManualScoreAdjustment[]

  /** 홈페이지 준비도 (website / ax_website 프로젝트) */
  websiteReadiness: WebsiteReadinessResult | null

  ruleVersion: string
  createdBy: string
  reviewedBy: string
  finalizedBy: string
  createdAt: string
  updatedAt: string
  reviewedAt: string | null
  finalizedAt: string | null
}

export type AssessmentResultInput = Omit<
  AssessmentResult,
  'id' | 'version' | 'createdAt' | 'updatedAt'
>

export interface AssessmentFilters {
  query?: string
  projectType?: 'ax' | 'ax_website' | 'website'
  status?: AssessmentStatus
  recommendation?: AssessmentRecommendation
  confidence?: AssessmentConfidence
  /** 점수 구간 하한/상한 */
  minScore?: number
  maxScore?: number
  needsReanalysis?: boolean
  ownerId?: string
}

export type AssessmentSortKey =
  | 'recent'
  | 'score_desc'
  | 'score_asc'
  | 'confidence_desc'
  | 'client_name'
