/* ------------------------------------------------------------------ */
/* 기관·자금 연계 및 성과관리 (Stage 11)                                 */
/*                                                                     */
/* 진단·설계·검증·제출자료 결과를 지원기관 접촉 전략, 준비자료, 진행이력,  */
/* 성과 KPI, 사례 자산으로 연결한다.                                     */
/* 실제 기관 승인 여부·확률·한도·금리를 자동 예측하지 않으며,             */
/* 공식 출처·확인일이 없는 정보는 '검토 필요'로 표시한다.                 */
/* ------------------------------------------------------------------ */

/* A. 기관 유형 */
export type InstitutionCategory =
  | 'policy_finance'
  | 'credit_guarantee'
  | 'technology_guarantee'
  | 'startup_support'
  | 'rnd_support'
  | 'employment_support'
  | 'local_government'
  | 'export_support'
  | 'certification'
  | 'investment'
  | 'private_finance'
  | 'other'

/* 출처 상태 */
export type SourceStatus =
  | 'official_verified'
  | 'user_entered'
  | 'reference_only'
  | 'stale'
  | 'unknown'

export interface InstitutionContactChannel {
  channel: OutreachChannel
  label: string
  value: string
  sensitive: boolean
}

/* B. 기관 */
export interface Institution {
  id: string
  name: string
  shortName: string
  category: InstitutionCategory
  description: string
  officialUrl: string
  contactChannels: InstitutionContactChannel[]
  regions: string[]
  targetIndustries: string[]
  targetCompanyStages: string[]
  targetCompanySizes: string[]
  typicalReviewFocus: string[]
  requiredBaselineEvidence: string[]
  cautionNotes: string
  sourceStatus: SourceStatus
  lastVerifiedAt: string | null
  validUntil: string | null
  createdAt: string
  updatedAt: string
  archivedAt: string | null
}

export type InstitutionInput = Omit<Institution, 'id' | 'createdAt' | 'updatedAt'>

/* C. 지원 유형 */
export type SupportType =
  | 'loan'
  | 'guarantee'
  | 'grant'
  | 'subsidy'
  | 'voucher'
  | 'rnd'
  | 'employment'
  | 'export'
  | 'certification'
  | 'investment'
  | 'tax_support'
  | 'consulting'
  | 'other'

/* D. 지원 프로그램 (예시 템플릿 또는 사용자 등록 — 실제 공고 아님) */
export interface SupportProgram {
  id: string
  institutionId: string
  name: string
  supportType: SupportType
  summary: string
  targetCompanies: string
  targetIndustries: string[]
  regions: string[]
  companyAgeRules: string
  revenueRules: string
  employeeRules: string
  creditRules: string
  technologyRules: string
  certificationRules: string
  requiredDocuments: string[]
  reviewFocus: string[]
  disqualifiers: string[]
  supportDescription: string
  /** 문자열만 — 근거 없는 금액 숫자 자동 생성 금지 */
  amountDescription: string
  costShareDescription: string
  /** 문자열만 — 자동으로 접수일을 만들지 않음 */
  scheduleDescription: string
  applicationMethod: string
  officialUrl: string
  announcementUrl: string
  sourceStatus: SourceStatus
  lastVerifiedAt: string | null
  validUntil: string | null
  notes: string
  isTemplate: boolean
  createdAt: string
  updatedAt: string
  archivedAt: string | null
}

export type SupportProgramInput = Omit<SupportProgram, 'id' | 'createdAt' | 'updatedAt'>

/* E. 정보 최신성 */
export type InformationFreshnessStatus = 'current' | 'review_due' | 'stale' | 'unknown'

/* F. 전략 상태 */
export type FundingStrategyStatus = 'draft' | 'reviewed' | 'finalized' | 'superseded'

/* G. 후보 우선순위 */
export type MatchPriority = 'primary' | 'secondary' | 'watch' | 'excluded'

/* H. 후보 신뢰도 (승인 확률 아님 — 추가 검토 우선도) */
export type MatchConfidence = 'high' | 'medium' | 'low' | 'insufficient_data'

/* I. 요건 충족 상태 (unknown과 not_met을 구분) */
export type CriterionStatus = 'met' | 'partially_met' | 'not_met' | 'unknown' | 'not_applicable'

export type CriterionCategory =
  | 'basic'
  | 'financial'
  | 'credit'
  | 'technology'
  | 'innovation'
  | 'employment'
  | 'certification'
  | 'market'
  | 'region'
  | 'documentation'
  | 'compliance'
  | 'other'

/* J. 프로그램 요건 점검 */
export interface ProgramCriterionCheck {
  id: string
  category: CriterionCategory
  label: string
  description: string
  status: CriterionStatus
  projectEvidenceIds: string[]
  missingEvidence: string
  analystNote: string
  sourceRule: string
  requiresOfficialConfirmation: boolean
}

/* K. 기관·프로그램 후보 */
export interface FundingMatch {
  id: string
  strategyId: string
  institutionId: string
  programId: string | null
  priority: MatchPriority
  confidence: MatchConfidence
  reasonSummary: string
  expectedUse: string
  criterionChecks: ProgramCriterionCheck[]
  strengths: string[]
  gaps: string[]
  risks: string[]
  requiredNextActions: string[]
  officialConfirmationRequired: string[]
  analystOpinion: string
  autoGenerated: boolean
  generationKey: string
  createdAt: string
  updatedAt: string
  excludedAt: string | null
  exclusionReason: string
}

/* L. 근거 출처 */
export type EvidenceSourceType =
  | 'organization'
  | 'project'
  | 'assessment'
  | 'selection'
  | 'mvp_design'
  | 'website_design'
  | 'validation'
  | 'deliverable'
  | 'manual'
  | 'external_document'

/* M. 근거 */
export interface FundingEvidence {
  id: string
  sourceType: EvidenceSourceType
  sourceId: string
  label: string
  description: string
  value: string
  unit: string
  evidenceDate: string
  verified: boolean
  verificationNote: string
  sensitive: boolean
  relatedMatchIds: string[]
  createdAt: string
  updatedAt: string
}

/* N. 부족조건 심각도 */
export type GapSeverity = 'info' | 'low' | 'medium' | 'high' | 'critical'
export type GapStatus = 'open' | 'in_progress' | 'resolved' | 'accepted' | 'not_applicable'

/* O. 부족조건 */
export interface FundingGap {
  id: string
  strategyId: string
  matchId: string | null
  category: CriterionCategory
  severity: GapSeverity
  title: string
  description: string
  requiredAction: string
  ownerId: string
  dueDate: string
  status: GapStatus
  evidenceNeeded: string
  resolution: string
  createdAt: string
  updatedAt: string
}

/* P. 접촉 채널 */
export type OutreachChannel =
  | 'phone'
  | 'email'
  | 'website'
  | 'visit'
  | 'referral'
  | 'briefing'
  | 'seminar'
  | 'consultant'
  | 'other'

export type OutreachPlanStatus = 'planned' | 'prepared' | 'contacted' | 'follow_up' | 'completed' | 'cancelled'

/* Q. 접촉 계획 */
export interface OutreachPlan {
  id: string
  strategyId: string
  institutionId: string
  programId: string | null
  purpose: string
  targetRole: string
  channel: OutreachChannel
  plannedDate: string
  ownerId: string
  preparationItems: string[]
  keyQuestions: string[]
  talkingPoints: string[]
  status: OutreachPlanStatus
  notes: string
  createdAt: string
  updatedAt: string
}

/* R. 접촉 기록 (과도한 개인 연락처 저장 금지) */
export interface OutreachActivity {
  id: string
  planId: string
  strategyId: string
  occurredAt: string
  channel: OutreachChannel
  contactRole: string
  contactNameNote: string
  summary: string
  institutionFeedback: string
  requestedMaterials: string[]
  nextAction: string
  nextActionDueDate: string
  internalOnly: boolean
  createdBy: string
  createdAt: string
}

/* S. 준비자료 상태 */
export type DocumentRequirementStatus =
  | 'missing'
  | 'requested'
  | 'received'
  | 'reviewing'
  | 'ready'
  | 'submitted'
  | 'not_required'

export type DocumentCategory =
  | 'company'
  | 'financial'
  | 'tax'
  | 'credit'
  | 'technology'
  | 'rnd'
  | 'employment'
  | 'certification'
  | 'market'
  | 'contract'
  | 'application'
  | 'consent'
  | 'other'

/* T. 준비자료 요건 */
export interface FundingDocumentRequirement {
  id: string
  strategyId: string
  matchId: string | null
  category: DocumentCategory
  title: string
  description: string
  status: DocumentRequirementStatus
  required: boolean
  sourceDeliverablePackageId: string
  sourceEvidenceIds: string[]
  ownerId: string
  dueDate: string
  officialFormRequired: boolean
  sensitive: boolean
  notes: string
  createdAt: string
  updatedAt: string
}

/* U. 신청 단계 */
export type ApplicationStage =
  | 'prospect'
  | 'pre_review'
  | 'preparing'
  | 'submitted'
  | 'reviewing'
  | 'supplement_requested'
  | 'supplement_submitted'
  | 'approved'
  | 'conditionally_approved'
  | 'rejected'
  | 'withdrawn'
  | 'on_hold'
  | 'completed'

/* V. 신청 (금액은 사용자가 실제 결과 입력 시에만 저장) */
export interface FundingApplication {
  id: string
  strategyId: string
  matchId: string | null
  applicationName: string
  applicationStage: ApplicationStage
  applicationReference: string
  submittedAt: string
  reviewStartedAt: string
  resultAt: string
  requestedAmount: string
  approvedAmount: string
  currency: string
  approvedConditions: string[]
  rejectionReasons: string[]
  supplementRequests: string[]
  nextAction: string
  ownerId: string
  notes: string
  createdAt: string
  updatedAt: string
}

/* W. 결과 유형 */
export type OutcomeType =
  | 'approved'
  | 'conditionally_approved'
  | 'rejected'
  | 'withdrawn'
  | 'on_hold'
  | 'not_applied'
  | 'pending'

/* X. 결과 */
export interface FundingOutcome {
  id: string
  strategyId: string
  applicationId: string
  type: OutcomeType
  summary: string
  requestedAmount: string
  approvedAmount: string
  executedAmount: string
  currency: string
  approvalDate: string
  executionDate: string
  conditions: string[]
  rejectionReasons: string[]
  lessonsLearned: string
  followUpActions: string[]
  evidenceIds: string[]
  recordedBy: string
  recordedAt: string
}

/* Y. 성과 지표 유형 */
export type OutcomeMetricType =
  | 'funding_amount'
  | 'guarantee_amount'
  | 'grant_amount'
  | 'interest_cost'
  | 'processing_days'
  | 'preparation_hours'
  | 'consulting_hours'
  | 'jobs_created'
  | 'revenue_change'
  | 'cost_reduction'
  | 'time_saved'
  | 'certification_obtained'
  | 'application_count'
  | 'approval_count'
  | 'other'

/* Z. 성과 지표 (근거 없는 baseline·target 자동 생성 금지) */
export interface OutcomeMetric {
  id: string
  strategyId: string
  outcomeId: string
  type: OutcomeMetricType
  name: string
  baselineValue: string
  targetValue: string
  actualValue: string
  unit: string
  measurementMethod: string
  measurementDate: string
  sourceEvidenceIds: string[]
  verified: boolean
  sensitive: boolean
  notes: string
}

/* AA. 사례 공개범위 */
export type CaseVisibility = 'internal' | 'anonymized' | 'customer_approved' | 'public'

/* AB. 사례 상태 */
export type CaseStudyStatus = 'draft' | 'review' | 'approved' | 'archived'

export type ConsentStatus = 'not_requested' | 'pending' | 'agreed' | 'declined' | 'not_required_internal'

/* AC. 사례 */
export interface CaseStudy {
  id: string
  projectId: string
  organizationId: string
  strategyId: string
  outcomeIds: string[]
  status: CaseStudyStatus
  visibility: CaseVisibility
  title: string
  industry: string
  companyProfile: string
  initialSituation: string
  keyProblems: string[]
  strategySummary: string
  selectedInstitutions: string[]
  selectedPrograms: string[]
  preparationActions: string[]
  timelineSummary: string
  outcomeSummary: string
  verifiedMetrics: string[]
  challenges: string[]
  lessons: string[]
  reusableInsights: string[]
  customerQuote: string
  consentStatus: ConsentStatus
  anonymizationNotes: string
  evidenceIds: string[]
  /** 자동 초안 원본 보존 */
  originalDraft: string
  manuallyEdited: boolean
  createdBy: string
  reviewedBy: string
  approvedBy: string
  createdAt: string
  updatedAt: string
  approvedAt: string | null
  archivedAt: string | null
}

export type CaseStudyInput = Omit<CaseStudy, 'id' | 'createdAt' | 'updatedAt'>

/* AD. 전략 품질검사 */
export type FundingQualitySeverity = 'info' | 'warning' | 'error'

export interface FundingQualityCheck {
  id: string
  severity: FundingQualitySeverity
  title: string
  description: string
  passed: boolean
  relatedIds: string[]
}

/* 내부 투입·사업성과 (민감정보 — 고객용 자동 가림) */
export interface InternalPerformance {
  leadConsultant: string
  internalMembers: string[]
  startDate: string
  endDate: string
  totalHours: string
  externalCost: string
  clientFee: string
  additionalContracts: string
  referrals: string
  renewals: string
  notes: string
}

/* 출처 스냅샷 참조 (확정 인계 내용) */
export interface FundingSourceReference {
  sourceType: EvidenceSourceType
  sourceId: string
  label: string
  version: number
  available: boolean
  capturedAt: string
}

/* AE. 연계 전략 (aggregate root) */
export interface FundingStrategy {
  id: string
  projectId: string
  organizationId: string
  version: number
  status: FundingStrategyStatus
  objective: string
  targetUse: string
  preferredSupportTypes: SupportType[]
  sourceSnapshot: FundingSourceReference[]
  sourceSnapshotHash: string
  evidence: FundingEvidence[]
  matches: FundingMatch[]
  gaps: FundingGap[]
  outreachPlans: OutreachPlan[]
  outreachActivities: OutreachActivity[]
  documentRequirements: FundingDocumentRequirement[]
  applications: FundingApplication[]
  outcomes: FundingOutcome[]
  metrics: OutcomeMetric[]
  internalPerformance: InternalPerformance
  qualityChecks: FundingQualityCheck[]
  strategySummary: string
  analystNotes: string
  officialConfirmationNotes: string
  openQuestions: string[]
  assumptions: string[]
  risks: string[]
  ruleVersion: string
  createdBy: string
  reviewedBy: string
  finalizedBy: string
  createdAt: string
  updatedAt: string
  reviewedAt: string | null
  finalizedAt: string | null
  supersededAt: string | null
}

export type FundingStrategyInput = Omit<FundingStrategy, 'id' | 'version' | 'createdAt' | 'updatedAt'>

/* AF. 전략 확정 스냅샷 (원본 변경과 무관하게 보존) */
export interface FundingStrategySnapshot {
  id: string
  strategyId: string
  projectId: string
  organizationId: string
  version: number
  objective: string
  targetUse: string
  selectedMatches: FundingMatch[]
  strengths: string[]
  gaps: FundingGap[]
  outreachPlan: OutreachPlan[]
  requiredDocuments: FundingDocumentRequirement[]
  applications: FundingApplication[]
  outcomes: FundingOutcome[]
  metrics: OutcomeMetric[]
  caseCandidate: boolean
  officialConfirmationNotes: string
  openQuestions: string[]
  assumptions: string[]
  risks: string[]
  generatedAt: string
}

export type FundingStrategySnapshotInput = Omit<FundingStrategySnapshot, 'id'>

export interface InstitutionFilters {
  query?: string
  category?: InstitutionCategory
  sourceStatus?: SourceStatus
}
export interface ProgramFilters {
  query?: string
  supportType?: SupportType
  institutionId?: string
  freshness?: InformationFreshnessStatus
}
export interface FundingStrategyFilters {
  query?: string
  status?: FundingStrategyStatus
  applicationStage?: ApplicationStage
  outcomeType?: OutcomeType
  caseCandidate?: boolean
}
export interface CaseStudyFilters {
  query?: string
  status?: CaseStudyStatus
  visibility?: CaseVisibility
}
