import type { MvpLevel } from './domain'
import type { RecommendedMvpTemplate } from './selection'

/* ------------------------------------------------------------------ */
/* MVP 설계 워크벤치 도메인 타입 (Stage 7)                               */
/*                                                                     */
/* 확정된 핵심 과제(SelectionHandoffSnapshot)를 실제 개발 가능한        */
/* 기능·화면·데이터·권한·검증 기준으로 변환하는 규칙 기반 설계 도메인.    */
/* 자동 생성값은 모두 확정 시점의 근거(candidate/evidence)에 연결되며,   */
/* 확정 스냅샷은 원본이 이후 바뀌어도 변하지 않는다.                     */
/* ------------------------------------------------------------------ */

/* A. 설계 라이프사이클 */
export type MvpDesignStatus = 'draft' | 'reviewed' | 'finalized' | 'superseded'

/* B. 기능 범위 분류 — 1차 MVP는 Must에 집중한다 */
export type FeatureScope = 'must' | 'should' | 'later' | 'excluded'

/* C. 기능 유형 */
export type FeatureType =
  | 'input_form'
  | 'list_view'
  | 'detail_view'
  | 'rule_calculation'
  | 'document_generation'
  | 'approval_flow'
  | 'notification'
  | 'dashboard_report'
  | 'search_filter'
  | 'data_validation'
  | 'status_tracking'
  | 'ai_assist'
  | 'integration'
  | 'admin_setting'
  | 'other'

/* D. 기능 자동화 방식 — 사람 최종판단이 필요한 영역을 명시한다 */
export type FeatureAutomationMode =
  | 'full_auto'
  | 'assisted'
  | 'human_confirm'
  | 'manual_only'

/* E. 처리 방식(입력→처리→출력에서 '처리'의 성격) */
export type ProcessingKind =
  | 'store'
  | 'rule_transform'
  | 'calculate'
  | 'classify'
  | 'aggregate'
  | 'generate_draft'
  | 'route_notify'
  | 'validate'
  | 'passthrough'

export interface FeatureEvidenceRef {
  /** 인계 스냅샷/후보에서의 근거 종류 */
  kind: 'candidate' | 'problem' | 'workflow' | 'kpi' | 'template' | 'dependency' | 'manual'
  label: string
  /** 원본 식별자(있으면) */
  sourceId: string
}

/* F. MVP 기능 */
export interface MvpFeature {
  id: string
  name: string
  summary: string
  scope: FeatureScope
  /** 자동 분류를 담당자가 바꿨을 때의 사유 */
  scopeReason: string
  type: FeatureType
  automationMode: FeatureAutomationMode
  /** 입력 / 처리 / 출력 — 기능명만이 아니라 실제 동작을 정의한다 */
  input: string
  processing: string
  processingKind: ProcessingKind
  output: string
  /** 연결된 화면·데이터·규칙(설계 일관성 확인용) */
  screenIds: string[]
  entityIds: string[]
  businessRuleIds: string[]
  /** AI 사용 여부와 전문가 최종판단 필요 여부 */
  usesAi: boolean
  humanReviewRequired: boolean
  /** 세무·노무·법률·의료 등 전문가 최종판단을 대체하면 안 되는 기능 */
  expertJudgmentBoundary: boolean
  evidence: FeatureEvidenceRef[]
  sourceTemplate: RecommendedMvpTemplate | null
  autoGenerated: boolean
  order: number
}

/* G. 업무 흐름(현재/목표) */
export type WorkflowKind = 'current' | 'desired'

export interface MvpWorkflowStep {
  id: string
  order: number
  actor: string
  action: string
  /** 이 단계가 MVP에서 자동화/보조되는지 */
  handledBy: 'system' | 'user' | 'system_and_user' | 'external'
  featureId: string | null
  note: string
}

export interface MvpWorkflow {
  kind: WorkflowKind
  summary: string
  steps: MvpWorkflowStep[]
}

/* H. 화면 정의 */
export type ScreenType =
  | 'list'
  | 'detail'
  | 'form'
  | 'dashboard'
  | 'wizard'
  | 'result'
  | 'setting'
  | 'auth'

export interface ScreenComponentDefinition {
  id: string
  label: string
  kind: 'table' | 'form_field' | 'button' | 'summary_card' | 'chart' | 'filter' | 'status' | 'text'
  description: string
}

export interface MvpScreen {
  id: string
  name: string
  type: ScreenType
  purpose: string
  primaryRoleId: string | null
  components: ScreenComponentDefinition[]
  featureIds: string[]
  scope: FeatureScope
  order: number
  autoGenerated: boolean
}

/* I. 데이터 엔티티 */
export type FieldType =
  | 'text'
  | 'long_text'
  | 'number'
  | 'currency'
  | 'date'
  | 'datetime'
  | 'boolean'
  | 'enum'
  | 'reference'
  | 'file'
  | 'computed'

export interface DataFieldDefinition {
  id: string
  name: string
  label: string
  type: FieldType
  required: boolean
  /** enum 값·참조 대상 등 부가 설명 */
  detail: string
  /** 개인정보·민감정보 여부(보안 규칙 연결) */
  sensitive: boolean
  /** 계산 필드일 때의 규칙 설명 */
  computedFrom: string
}

export interface MvpDataEntity {
  id: string
  name: string
  label: string
  description: string
  fields: DataFieldDefinition[]
  /** 이 엔티티를 생성/수정하는 기능 */
  ownedByFeatureIds: string[]
  hasSensitiveData: boolean
  order: number
  autoGenerated: boolean
}

/* J. 역할·권한 */
export type RolePermissionAction = 'create' | 'read' | 'update' | 'delete' | 'approve' | 'export'

export interface PermissionRule {
  id: string
  roleId: string
  entityId: string
  actions: RolePermissionAction[]
  /** 조건부 권한 설명(예: 본인 담당 건만) */
  condition: string
}

export interface MvpRole {
  id: string
  name: string
  description: string
  /** 진단·선정에서 확인된 실제 사용자 역할과의 연결 */
  sourceUsers: string
  isPrimaryUser: boolean
  order: number
  autoGenerated: boolean
}

/* K. 비즈니스 규칙 — 예쁜 화면이 아니라 업무 규칙을 정의한다 */
export type BusinessRuleType =
  | 'validation'
  | 'calculation'
  | 'classification'
  | 'routing'
  | 'threshold'
  | 'permission'
  | 'lifecycle'
  | 'exception'

export interface BusinessRule {
  id: string
  name: string
  type: BusinessRuleType
  /** 조건 → 결과 형태로 규칙을 기술 */
  condition: string
  outcome: string
  /** 규칙이 확정되지 않아 담당자 확인이 필요한 경우 */
  needsConfirmation: boolean
  evidence: FeatureEvidenceRef[]
  featureId: string | null
  autoGenerated: boolean
  order: number
}

/* L. AI 기능 계획 — 불필요한 곳에 AI를 넣지 않는다 */
export type AiFeaturePurpose =
  | 'draft_generation'
  | 'summarization'
  | 'classification'
  | 'extraction'
  | 'recommendation'
  | 'qna_support'

export interface MvpAiFeature {
  id: string
  name: string
  purpose: AiFeaturePurpose
  /** 왜 규칙 기반이 아니라 AI가 필요한지 */
  justification: string
  /** AI 출력은 초안이며 사람이 확정한다 */
  humanConfirms: boolean
  /** 전문가 최종판단을 대체하지 않는다 */
  expertJudgmentBoundary: boolean
  fallback: string
  featureId: string | null
  order: number
}

/* M. 외부 연동 계획 */
export type IntegrationReadiness = 'ready' | 'needs_setup' | 'blocked' | 'deferred'

export interface MvpIntegration {
  id: string
  name: string
  target: string
  purpose: string
  readiness: IntegrationReadiness
  /** 준비되지 않으면 1차 범위에서 제외하고 대체 방식을 명시 */
  fallbackWhenNotReady: string
  requiredBeforeMvp: boolean
  order: number
}

/* N. 예외·오류 시나리오 */
export type ExceptionKind =
  | 'invalid_input'
  | 'missing_data'
  | 'permission_denied'
  | 'external_failure'
  | 'conflict'
  | 'expert_required'
  | 'edge_case'

export interface ExceptionScenario {
  id: string
  kind: ExceptionKind
  situation: string
  handling: string
  featureId: string | null
  order: number
}

/* O. 수용 기준(검증 가능한 완료 조건) */
export interface AcceptanceCriterion {
  id: string
  featureId: string | null
  /** Given / When / Then 형태의 검증 기준 */
  given: string
  when: string
  then: string
  measurable: boolean
  order: number
}

/* P. 테스트 시나리오 */
export type TestScenarioKind = 'happy_path' | 'validation' | 'permission' | 'exception' | 'boundary'

export interface TestScenario {
  id: string
  title: string
  kind: TestScenarioKind
  steps: string[]
  expected: string
  featureId: string | null
  order: number
}

/* Q. KPI 정의 — 측정 가능한 성과 기준 */
export type KpiDirection = 'increase' | 'decrease' | 'maintain'

export interface KpiDefinition {
  id: string
  name: string
  direction: KpiDirection
  baseline: string
  target: string
  unit: string
  measureMethod: string
  /** 근거가 없어 목표를 산정할 수 없는 경우 */
  notEstimable: boolean
  sourceKpi: string
  order: number
}

/* R. 범위 가드레일 점검 */
export type GuardrailKey =
  | 'single_core_task'
  | 'max_roles'
  | 'max_screens'
  | 'max_forms'
  | 'max_ai_features'
  | 'max_reports'
  | 'max_external_api'
  | 'no_native_app'
  | 'no_full_erp'
  | 'no_payment'
  | 'no_multi_tenant'
  | 'no_expert_replacement'

export type GuardrailStatus = 'ok' | 'warning' | 'exceeded'

export interface ScopeGuardrailCheck {
  key: GuardrailKey
  label: string
  limit: number | null
  actual: number | null
  status: GuardrailStatus
  message: string
}

/* S. 설계 품질 점검 — error는 확정을 막는다 */
export type QualityCheckSeverity = 'error' | 'warning' | 'info'
export type QualityCheckCode =
  | 'no_must_feature'
  | 'feature_missing_io'
  | 'feature_missing_evidence'
  | 'must_without_acceptance'
  | 'screen_over_limit'
  | 'role_over_limit'
  | 'form_over_limit'
  | 'ai_over_limit'
  | 'report_over_limit'
  | 'api_over_limit'
  | 'ai_without_justification'
  | 'expert_boundary_missing'
  | 'unmet_dependency'
  | 'no_kpi'
  | 'mvp_level_high'
  | 'website_track_pending'
  | 'rule_needs_confirmation'

export interface MvpDesignQualityCheck {
  code: QualityCheckCode
  severity: QualityCheckSeverity
  message: string
  /** 연결된 항목(있으면) */
  relatedId: string
}

/* T. MVP 수준 결정 */
export interface MvpLevelDecision {
  recommendedLevel: MvpLevel
  selectedLevel: MvpLevel
  /** 추천과 다른 수준을 선택했을 때의 사유(필수) */
  overrideReason: string
  rationale: string
}

/* U. 설계 집계 루트 */
export interface MvpDesign {
  id: string
  projectId: string
  organizationId: string
  /** 근거가 된 확정 선정·인계 스냅샷 */
  selectionDecisionId: string
  selectionVersion: number
  handoffSnapshotId: string
  version: number
  status: MvpDesignStatus

  coreTaskName: string
  problemStatement: string
  targetUsers: string
  goalStatement: string

  levelDecision: MvpLevelDecision

  workflows: MvpWorkflow[]
  features: MvpFeature[]
  screens: MvpScreen[]
  entities: MvpDataEntity[]
  roles: MvpRole[]
  permissions: PermissionRule[]
  businessRules: BusinessRule[]
  aiFeatures: MvpAiFeature[]
  integrations: MvpIntegration[]
  exceptions: ExceptionScenario[]
  acceptanceCriteria: AcceptanceCriterion[]
  testScenarios: TestScenario[]
  kpis: KpiDefinition[]

  guardrailChecks: ScopeGuardrailCheck[]
  qualityChecks: MvpDesignQualityCheck[]

  /** 담당자 최종 설계 의견(확정 필수) */
  designSummary: string
  autoSummary: string
  scopeNotes: string
  outOfScope: string[]

  hasWebsiteTrack: boolean
  websiteStudioRecommended: boolean

  sourceSnapshotHash: string
  ruleVersion: string
  createdBy: string
  reviewedBy: string
  finalizedBy: string
  createdAt: string
  updatedAt: string
  reviewedAt: string | null
  finalizedAt: string | null
  supersededAt: string | null
}

export type MvpDesignInput = Omit<
  MvpDesign,
  'id' | 'version' | 'createdAt' | 'updatedAt'
>

/* AK. Stage 8 인계 스냅샷 — 확정 시점 동결 */
export interface DesignHandoffFeature {
  name: string
  scope: FeatureScope
  type: FeatureType
  automationMode: FeatureAutomationMode
  input: string
  processing: string
  output: string
  usesAi: boolean
  humanReviewRequired: boolean
  expertJudgmentBoundary: boolean
  acceptanceCount: number
}

export interface MvpDesignHandoffSnapshot {
  id: string
  projectId: string
  organizationId: string
  mvpDesignId: string
  designVersion: number

  coreTaskName: string
  problemStatement: string
  targetUsers: string
  goalStatement: string
  selectedLevel: MvpLevel

  mustFeatures: DesignHandoffFeature[]
  shouldFeatures: DesignHandoffFeature[]
  laterFeatures: string[]
  excludedFeatures: string[]

  screenNames: string[]
  entityNames: string[]
  roleNames: string[]
  aiFeatureNames: string[]
  integrationNames: string[]
  kpiSummaries: string[]
  keyBusinessRules: string[]
  outOfScope: string[]

  hasWebsiteTrack: boolean
  websiteStudioRecommended: boolean

  sourceSelectionVersion: number
  ruleVersion: string
  generatedAt: string
}

export type MvpDesignHandoffInput = Omit<MvpDesignHandoffSnapshot, 'id'>

export interface MvpDesignFilters {
  query?: string
  status?: MvpDesignStatus
  projectType?: 'ax' | 'ax_website' | 'website'
  needsRedesign?: boolean
}
