import type { WebsiteReadinessResult } from './assessment'

/* ------------------------------------------------------------------ */
/* 홈페이지 설계 스튜디오 도메인 타입 (Stage 8)                          */
/*                                                                     */
/* 홈페이지 사전진단 결과를 사이트 구조·페이지·섹션·콘텐츠·디자인 방향·   */
/* 개발 지시문으로 변환하는 규칙 기반 설계 도메인. 자동 생성값은 결정적   */
/* 이며, 확정 스냅샷은 이후 원본이 바뀌어도 변하지 않는다.               */
/* ------------------------------------------------------------------ */

/* A. 설계 라이프사이클 */
export type WebsiteDesignStatus = 'draft' | 'reviewed' | 'finalized' | 'superseded'

/* B. 홈페이지 유형 */
export type WebsiteType =
  | 'corporate'
  | 'service'
  | 'lead_generation'
  | 'landing_page'
  | 'portfolio'
  | 'recruitment'
  | 'ecommerce_catalog'
  | 'mixed'

/* C. 전환 행동 유형 */
export type ConversionActionType =
  | 'inquiry'
  | 'diagnosis_request'
  | 'consultation_request'
  | 'phone_call'
  | 'message'
  | 'booking'
  | 'quote_request'
  | 'download'
  | 'purchase_external'
  | 'visit'
  | 'other'

export type ConversionPriority = 'primary' | 'secondary' | 'optional'

/* D. 전환 행동 */
export interface WebsiteConversionAction {
  id: string
  type: ConversionActionType
  label: string
  description: string
  priority: ConversionPriority
  targetPageId: string | null
  buttonText: string
  destination: string
  trackingRequired: boolean
}

/* E. 핵심 고객 */
export type AudiencePriority = 'primary' | 'secondary'

export interface WebsiteAudience {
  id: string
  name: string
  description: string
  problems: string[]
  desiredOutcomes: string[]
  objections: string[]
  trustNeeds: string[]
  priority: AudiencePriority
  sourceEvidenceIds: string[]
}

/* F. 전략 */
export interface WebsiteStrategy {
  purpose: string
  businessGoal: string
  websiteType: WebsiteType
  websiteTypeReason: string
  websiteTypeOverrideReason: string
  primaryAudienceId: string | null
  audiences: WebsiteAudience[]
  primaryConversionActionId: string | null
  conversionActions: WebsiteConversionAction[]
  keyMessage: string
  differentiation: string
  trustStrategy: string
  toneOfVoice: string
  successMetrics: string[]
  assumptions: string[]
  openQuestions: string[]
}

/* G. 페이지 유형 */
export type WebsitePageType =
  | 'home'
  | 'about'
  | 'service'
  | 'service_detail'
  | 'case_studies'
  | 'case_detail'
  | 'process'
  | 'pricing'
  | 'faq'
  | 'resources'
  | 'contact'
  | 'diagnosis'
  | 'landing'
  | 'recruitment'
  | 'privacy'
  | 'terms'
  | 'custom'

export type WebsitePageStatus = 'required' | 'recommended' | 'later' | 'excluded'

/* H. 페이지 */
export interface WebsitePageSeo {
  titleDirection: string
  descriptionDirection: string
  primaryTopic: string
  supportingTopics: string[]
  headingStructure: string[]
  internalLinks: string[]
  schemaTypeSuggestions: string[]
  indexable: boolean
  notes: string
}

export interface WebsitePage {
  id: string
  designId: string
  name: string
  slug: string
  pageType: WebsitePageType
  purpose: string
  targetAudienceIds: string[]
  primaryMessage: string
  primaryConversionActionId: string | null
  sections: WebsiteSection[]
  seo: WebsitePageSeo
  navigation: boolean
  status: WebsitePageStatus
  orderIndex: number
  autoGenerated: boolean
  createdAt: string
  updatedAt: string
  archivedAt: string | null
}

/* I. 섹션 유형 */
export type WebsiteSectionType =
  | 'hero'
  | 'problem'
  | 'solution'
  | 'services'
  | 'benefits'
  | 'differentiation'
  | 'process'
  | 'numbers'
  | 'trust'
  | 'cases'
  | 'testimonials'
  | 'team'
  | 'faq'
  | 'pricing'
  | 'comparison'
  | 'content'
  | 'gallery'
  | 'video'
  | 'map'
  | 'contact'
  | 'conversion'
  | 'footer'
  | 'custom'

export type SectionContentStatus = 'ready' | 'partial' | 'missing' | 'not_required'
export type SectionScope = 'required' | 'recommended' | 'later' | 'excluded'

/* J. 섹션 */
export interface WebsiteSection {
  id: string
  pageId: string
  sectionType: WebsiteSectionType
  title: string
  purpose: string
  keyMessage: string
  supportingContent: string[]
  contentItems: string[]
  visualDirection: string
  ctaActionId: string | null
  requiredAssets: string[]
  contentStatus: SectionContentStatus
  mobileBehavior: string
  scope: SectionScope
  notes: string
  orderIndex: number
  autoGenerated: boolean
}

/* K/L. 콘텐츠 항목 */
export type WebsiteContentItemType =
  | 'headline'
  | 'paragraph'
  | 'bullet'
  | 'service_description'
  | 'company_introduction'
  | 'number'
  | 'case_study'
  | 'testimonial'
  | 'faq'
  | 'pricing'
  | 'team_profile'
  | 'contact_info'
  | 'legal'
  | 'other'

export type ContentItemStatus = 'ready' | 'draft' | 'missing' | 'needs_review'
export type ContentItemSource =
  | 'survey'
  | 'existing_website'
  | 'company_document'
  | 'interview'
  | 'manual'
  | 'unknown'

export interface WebsiteContentItem {
  id: string
  type: WebsiteContentItemType
  title: string
  description: string
  status: ContentItemStatus
  source: ContentItemSource
  owner: string
  dueDate: string
  relatedPageIds: string[]
  relatedSectionIds: string[]
  required: boolean
  notes: string
}

/* M/N. 자산 요구사항 (실제 파일은 저장하지 않고 요구사항·준비상태만) */
export type WebsiteAssetType =
  | 'logo'
  | 'brand_guide'
  | 'company_photo'
  | 'team_photo'
  | 'service_photo'
  | 'product_photo'
  | 'case_image'
  | 'icon'
  | 'video'
  | 'illustration'
  | 'certificate'
  | 'map'
  | 'other'

export type AssetStatus = 'ready' | 'partial' | 'missing' | 'replacement_possible'

export interface WebsiteAssetRequirement {
  id: string
  type: WebsiteAssetType
  title: string
  description: string
  status: AssetStatus
  required: boolean
  quantity: number
  preferredRatio: string
  preferredResolution: string
  source: string
  relatedPageIds: string[]
  relatedSectionIds: string[]
  notes: string
}

/* O. 브랜드 성격 */
export type BrandPersonality =
  | 'professional'
  | 'trustworthy'
  | 'modern'
  | 'premium'
  | 'friendly'
  | 'energetic'
  | 'calm'
  | 'technical'
  | 'minimal'
  | 'bold'
  | 'warm'
  | 'traditional'

/* P. 디자인 방향 */
export type SpacingDensity = 'compact' | 'balanced' | 'spacious'
export type CornerStyle = 'square' | 'subtle' | 'rounded' | 'pill_limited'
export type MotionStyle = 'none' | 'subtle' | 'moderate'

export interface DesignDirection {
  personalities: BrandPersonality[]
  moodDescription: string
  primaryColorDirection: string
  secondaryColorDirection: string
  accentColorDirection: string
  backgroundDirection: string
  typographyDirection: string
  headingStyle: string
  bodyStyle: string
  spacingDensity: SpacingDensity
  cornerStyle: CornerStyle
  shadowStyle: string
  imageStyle: string
  iconStyle: string
  motionStyle: MotionStyle
  layoutPrinciples: string[]
  mobilePrinciples: string[]
  accessibilityPrinciples: string[]
  prohibitedStyles: string[]
  referenceNotes: string
}

/* R. 기술 범위 */
export type FrameworkPreference =
  | 'unspecified'
  | 'react_vite'
  | 'nextjs'
  | 'static_html'
  | 'webflow'
  | 'wordpress'
  | 'other'

export interface WebsiteTechnicalScope {
  frameworkPreference: FrameworkPreference
  responsive: boolean
  mobileFirst: boolean
  cmsRequired: boolean
  adminRequired: boolean
  forms: boolean
  integrations: boolean
  analytics: boolean
  seoBasics: boolean
  accessibilityLevel: string
  performanceGoal: string
  hostingPreference: string
  excludedTechnicalScope: string[]
  notes: string
}

/* S. 폼 요구사항 */
export interface WebsiteFormRequirement {
  id: string
  name: string
  purpose: string
  fields: string[]
  required: boolean
  destination: string
  confirmationBehavior: string
  privacyConsentRequired: boolean
  spamProtectionRequired: boolean
  relatedPageIds: string[]
}

/* T/U. 외부 연동 */
export type WebsiteIntegrationType =
  | 'analytics'
  | 'search_console'
  | 'map'
  | 'phone'
  | 'email'
  | 'messaging'
  | 'booking'
  | 'crm'
  | 'payment_external'
  | 'social'
  | 'video'
  | 'form_backend'
  | 'other'

export interface WebsiteIntegrationRequirement {
  id: string
  type: WebsiteIntegrationType
  name: string
  purpose: string
  requiredForLaunch: boolean
  setupOwner: string
  dependency: string
  fallback: string
  notes: string
}

/* V. 범위 가드레일 */
export type GuardrailStatus = 'pass' | 'warning' | 'exceeded'

export interface WebsiteScopeGuardrail {
  key: string
  label: string
  currentValue: number | null
  limitValue: number | null
  status: GuardrailStatus
  explanation: string
  relatedIds: string[]
}

/* W. 품질검사 */
export type QualitySeverity = 'info' | 'warning' | 'error'

export interface WebsiteQualityCheck {
  id: string
  severity: QualitySeverity
  title: string
  description: string
  passed: boolean
  relatedIds: string[]
}

/* X/Y. 개발 지시문 */
export type WebsitePromptType = 'claude_code' | 'generic_builder' | 'design_only' | 'content_only'

export interface GeneratedWebsitePrompt {
  id: string
  type: WebsitePromptType
  title: string
  content: string
  generatedFromVersion: number
  generatedAt: string
  manuallyEdited: boolean
  editNotes: string
}

/* Z. 설계 집계 루트 */
export interface WebsiteDesign {
  id: string
  projectId: string
  organizationId: string
  assessmentId: string
  version: number
  status: WebsiteDesignStatus
  name: string
  websiteReadinessSnapshot: WebsiteReadinessResult | null
  sourceResponseIds: string[]
  sourceEvidenceIds: string[]

  strategy: WebsiteStrategy
  pages: WebsitePage[]
  contentItems: WebsiteContentItem[]
  assetRequirements: WebsiteAssetRequirement[]
  designDirection: DesignDirection
  technicalScope: WebsiteTechnicalScope
  forms: WebsiteFormRequirement[]
  integrations: WebsiteIntegrationRequirement[]
  scopeGuardrails: WebsiteScopeGuardrail[]
  qualityChecks: WebsiteQualityCheck[]
  generatedPrompts: GeneratedWebsitePrompt[]

  designSummary: string
  finalNotes: string
  assumptions: string[]
  openQuestions: string[]
  risks: string[]

  ruleVersion: string
  sourceSnapshotHash: string
  createdBy: string
  reviewedBy: string
  finalizedBy: string
  createdAt: string
  updatedAt: string
  reviewedAt: string | null
  finalizedAt: string | null
  supersededAt: string | null
}

export type WebsiteDesignInput = Omit<
  WebsiteDesign,
  'id' | 'version' | 'createdAt' | 'updatedAt'
>

/* AA. 인계 스냅샷 (확정 시점 동결) */
export interface WebsiteHandoffPage {
  name: string
  slug: string
  pageType: WebsitePageType
  status: WebsitePageStatus
  purpose: string
  sectionTitles: string[]
}

export interface WebsiteDesignHandoffSnapshot {
  id: string
  projectId: string
  organizationId: string
  websiteDesignId: string
  version: number

  strategy: WebsiteStrategy
  sitemap: string[]
  pages: WebsiteHandoffPage[]
  contentRequirements: string[]
  assetRequirements: string[]
  designDirection: DesignDirection
  technicalScope: WebsiteTechnicalScope
  forms: WebsiteFormRequirement[]
  integrations: WebsiteIntegrationRequirement[]
  qualityChecks: WebsiteQualityCheck[]
  selectedPrompt: GeneratedWebsitePrompt | null

  assumptions: string[]
  openQuestions: string[]
  risks: string[]
  sourceAssessmentVersion: number
  generatedAt: string
}

export type WebsiteDesignHandoffInput = Omit<WebsiteDesignHandoffSnapshot, 'id'>

export interface WebsiteDesignFilters {
  query?: string
  status?: WebsiteDesignStatus
  websiteType?: WebsiteType
}
