import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, FileUp, Save } from 'lucide-react'
import { useAuth } from '../auth/AuthProvider'
import { getDataModeConfig } from '../data/dataMode'
import { listOperationsClients, OPERATIONS_DOCUMENTS, OPERATIONS_TASKS, saveOperationsClient, uploadOperationsDocument, type OperationsClient, type OperationsDocumentKey, type OperationsTaskKey } from '../services/operationsClientService'
import { Button } from '../components/ui/Button'
import { PageHeader } from '../components/ui/PageHeader'
import { Panel } from '../components/ui/Panel'

const statusLabel = { active: '진행 중', waiting: '고객 응답 대기', paused: '보류', completed: '완료' } as const

function ClientDetailContent({ workspaceId }: { workspaceId: string | null }) {
  const { clientId } = useParams()
  const [record, setRecord] = useState<OperationsClient | null>(null)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState('')
  useEffect(() => { void (async () => { try { const all = await listOperationsClients(workspaceId); setRecord(all.find((item) => item.id === clientId) ?? null) } finally { setLoading(false) } })() }, [clientId, workspaceId])
  const change = <K extends keyof OperationsClient>(key: K, value: OperationsClient[K]) => setRecord((current) => current ? { ...current, [key]: value } : current)
  const save = async () => { if (!record) return; try { setSaving(true); setRecord(await saveOperationsClient(record)); setMessage('저장했습니다.') } catch (cause) { setMessage(cause instanceof Error ? cause.message : '저장하지 못했습니다.') } finally { setSaving(false) } }
  const attach = async (key: OperationsDocumentKey, file: File) => { const current = record; if (!current) return; try { setSaving(true); setRecord(await uploadOperationsDocument(current, key, file)); setMessage(`${file.name} 파일을 보관했습니다.`) } catch (cause) { setMessage(cause instanceof Error ? cause.message : '파일을 보관하지 못했습니다.') } finally { setSaving(false) } }
  if (loading) return <p className="py-10 text-sm text-slate-500">불러오는 중...</p>
  if (!record) return <div className="space-y-4"><Link to="/ops/clients" className="inline-flex items-center gap-1 text-sm text-brand-700"><ArrowLeft className="size-4" />고객 운영으로</Link><Panel className="p-8 text-center text-slate-500">고객을 찾을 수 없습니다.</Panel></div>
  const updateTask = (key: OperationsTaskKey, patch: Partial<OperationsClient['tasks'][OperationsTaskKey]>) => change('tasks', { ...record.tasks, [key]: { ...record.tasks[key], ...patch } })
  const updateDocument = (key: OperationsDocumentKey, received: boolean) => change('documents', { ...record.documents, [key]: { ...record.documents[key], received, updatedAt: received ? new Date().toISOString() : null } })
  return <div className="space-y-6">
    <PageHeader title={record.companyName} description="업무, 서류, 수금, 지원사업 준비 상태를 저장합니다." actions={<div className="flex items-center gap-2"><Link to="/ops/clients" className="inline-flex min-h-10 items-center gap-1 px-2 text-sm font-medium text-slate-600"><ArrowLeft className="size-4" />목록</Link><Button onClick={() => void save()} disabled={saving}><Save className="size-4" />{saving ? '저장 중...' : '저장'}</Button></div>} />
    {message && <p role="status" className="rounded-(--radius-control) bg-brand-50 px-4 py-3 text-sm text-brand-800">{message}</p>}
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.45fr)_minmax(300px,0.8fr)]">
      <div className="space-y-5">
        <Panel className="overflow-hidden"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold text-slate-900">기본 업무</h2><p className="mt-1 text-sm text-slate-500">계약 후 항상 확인하는 항목입니다.</p></div><ul className="divide-y divide-slate-100">{OPERATIONS_TASKS.map(([key, label]) => <li key={key} className="px-5 py-4"><div className="flex items-center gap-3"><input aria-label={`${label} 완료`} type="checkbox" checked={record.tasks[key].completed} onChange={(event) => updateTask(key, { completed: event.target.checked })} className="size-5 accent-brand-600" /><strong className={`flex-1 text-sm ${record.tasks[key].completed ? 'text-slate-400 line-through' : 'text-slate-800'}`}>{label}</strong><input type="date" value={record.tasks[key].dueDate} onChange={(event) => updateTask(key, { dueDate: event.target.value })} className="w-32 rounded border border-slate-300 px-2 py-1.5 text-xs" /></div><input value={record.tasks[key].note} onChange={(event) => updateTask(key, { note: event.target.value })} placeholder="진행 메모" className="mt-2 w-full border-b border-slate-200 bg-transparent py-1.5 text-sm outline-none focus:border-brand-500" /></li>)}</ul></Panel>
        <Panel className="overflow-hidden"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold text-slate-900">필수 자료</h2><p className="mt-1 text-sm text-slate-500">수령 여부를 체크하고, 클라우드 연결 후 파일을 비공개로 보관합니다.</p></div><ul className="grid divide-y divide-slate-100 sm:grid-cols-2 sm:divide-x">{OPERATIONS_DOCUMENTS.map(([key, label]) => <li key={key} className="flex items-center gap-3 px-4 py-3"><input aria-label={`${label} 수령`} type="checkbox" checked={record.documents[key].received} onChange={(event) => updateDocument(key, event.target.checked)} className="size-5 accent-brand-600" /><span className="min-w-0 flex-1 truncate text-sm text-slate-700">{record.documents[key].fileName || label}</span>{getDataModeConfig().mode === 'supabase' ? <label title={`${label} 파일 첨부`} className="cursor-pointer text-slate-400 hover:text-brand-600"><FileUp className="size-4" /><input aria-label={`${label} 파일 첨부`} type="file" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) void attach(key, file); event.currentTarget.value = '' }} /></label> : <FileUp className="size-4 text-slate-300" />}</li>)}</ul></Panel>
      </div>
      <div className="space-y-5">
        <Panel className="p-5"><h2 className="font-semibold text-slate-900">고객 정보</h2><div className="mt-4 grid gap-3">{([['contactName', '담당자'], ['contactPhone', '연락처'], ['contactEmail', '이메일'], ['businessNumber', '사업자등록번호'], ['corporateNumber', '법인번호'], ['businessAddress', '사업장 주소'], ['industry', '업종']] as const).map(([key, label]) => <label key={key} className="text-xs font-medium text-slate-600">{label}<input value={record[key]} onChange={(event) => change(key, event.target.value)} className="mt-1 w-full rounded border border-slate-300 px-3 py-2 text-sm text-slate-800" /></label>)}<label className="text-xs font-medium text-slate-600">진행 상태<select value={record.status} onChange={(event) => change('status', event.target.value as OperationsClient['status'])} className="mt-1 w-full rounded border border-slate-300 px-3 py-2 text-sm text-slate-800">{Object.entries(statusLabel).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label></div></Panel>
        <Panel className="p-5"><h2 className="font-semibold text-slate-900">다음 할 일</h2><input value={record.nextAction} onChange={(event) => change('nextAction', event.target.value)} placeholder="다음에 처리할 내용을 적어두세요" className="mt-3 w-full rounded border border-slate-300 px-3 py-2 text-sm" /><input type="date" value={record.nextActionDueDate} onChange={(event) => change('nextActionDueDate', event.target.value)} className="mt-2 w-full rounded border border-slate-300 px-3 py-2 text-sm" /></Panel>
        <Panel className="p-5"><h2 className="font-semibold text-slate-900">계약·수금</h2><div className="mt-3 grid gap-3">{([['contractDepositAmount', '계약금'], ['successFeeAmount', '성공보수']] as const).map(([key, label]) => <label key={key} className="text-xs font-medium text-slate-600">{label}<input type="number" min="0" value={record[key] ?? ''} onChange={(event) => change(key, event.target.value === '' ? null : Number(event.target.value))} className="mt-1 w-full rounded border border-slate-300 px-3 py-2 text-sm" /></label>)}<label className="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" checked={record.contractDepositReceived} onChange={(event) => change('contractDepositReceived', event.target.checked)} className="size-4 accent-brand-600" />계약금 수령</label><label className="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" checked={record.successFeeReceived} onChange={(event) => change('successFeeReceived', event.target.checked)} className="size-4 accent-brand-600" />성공보수 수령</label></div></Panel>
        <Panel className="p-5"><h2 className="font-semibold text-slate-900">정책자금·지원사업</h2><input value={record.fundingStatus} onChange={(event) => change('fundingStatus', event.target.value)} placeholder="예: 2026 혁신바우처 검토 중" className="mt-3 w-full rounded border border-slate-300 px-3 py-2 text-sm" /><textarea value={record.fundingNote} onChange={(event) => change('fundingNote', event.target.value)} placeholder="컨택, 사업계획서, 보완자료 진행 메모" className="mt-2 min-h-24 w-full rounded border border-slate-300 px-3 py-2 text-sm" /></Panel>
      </div>
    </div>
  </div>
}

function CloudClientDetail() { const { currentWorkspaceId } = useAuth(); return <ClientDetailContent workspaceId={currentWorkspaceId} /> }
export function OperationsClientDetailPage() { return getDataModeConfig().mode === 'supabase' ? <CloudClientDetail /> : <ClientDetailContent workspaceId={null} /> }
