import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, CalendarDays, Check, CircleCheck, FileUp, Save } from 'lucide-react'
import { useAuth } from '../auth/AuthProvider'
import { getDataModeConfig } from '../data/dataMode'
import { listOperationsClients, OPERATIONS_DOCUMENTS, OPERATIONS_TASKS, operationsProgress, saveOperationsClient, uploadOperationsDocument, type OperationsClient, type OperationsDocumentKey, type OperationsTaskKey } from '../services/operationsClientService'
import { Button } from '../components/ui/Button'
import { PageHeader } from '../components/ui/PageHeader'
import { Panel } from '../components/ui/Panel'

const statusLabel = { active: '진행 중', waiting: '고객 응답 대기', paused: '보류', completed: '완료' } as const

function dateFromToday(days: number) { const date = new Date(); date.setDate(date.getDate() + days); return date.toISOString().slice(0, 10) }

function ClientDetailContent({ workspaceId }: { workspaceId: string | null }) {
  const { clientId } = useParams()
  const [record, setRecord] = useState<OperationsClient | null>(null)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState('')
  useEffect(() => { void (async () => { try { const all = await listOperationsClients(workspaceId); setRecord(all.find((item) => item.id === clientId) ?? null) } finally { setLoading(false) } })() }, [clientId, workspaceId])
  const progress = useMemo(() => record ? operationsProgress(record) : { tasks: 0, documents: 0, payment: 0 }, [record])
  const percent = Math.round(((progress.tasks + progress.documents + progress.payment) / 17) * 100)
  const change = <K extends keyof OperationsClient>(key: K, value: OperationsClient[K]) => setRecord((current) => current ? { ...current, [key]: value } : current)
  const persist = async (next: OperationsClient, confirmation = '저장했습니다.') => { try { setSaving(true); setRecord(await saveOperationsClient(next)); setMessage(confirmation) } catch (cause) { setMessage(cause instanceof Error ? cause.message : '저장하지 못했습니다.') } finally { setSaving(false) } }
  const save = () => { if (record) void persist(record) }
  const attach = async (key: OperationsDocumentKey, file: File) => { if (!record) return; try { setSaving(true); setRecord(await uploadOperationsDocument(record, key, file)); setMessage(`${file.name} 파일을 보관했습니다.`) } catch (cause) { setMessage(cause instanceof Error ? cause.message : '파일을 보관하지 못했습니다.') } finally { setSaving(false) } }
  if (loading) return <p className="py-10 text-sm text-slate-500">불러오는 중...</p>
  if (!record) return <div className="space-y-4"><Link to="/ops/clients" className="inline-flex items-center gap-1 text-sm text-brand-700"><ArrowLeft className="size-4" />고객 운영으로</Link><Panel className="p-8 text-center text-slate-500">고객을 찾을 수 없습니다.</Panel></div>
  const taskUpdate = (key: OperationsTaskKey, patch: Partial<OperationsClient['tasks'][OperationsTaskKey]>, immediate = false) => { const next = { ...record, tasks: { ...record.tasks, [key]: { ...record.tasks[key], ...patch } } }; setRecord(next); if (immediate) void persist(next, patch.completed ? '업무를 완료로 처리했습니다.' : '업무 상태를 변경했습니다.') }
  const documentUpdate = (key: OperationsDocumentKey, received: boolean) => { const next = { ...record, documents: { ...record.documents, [key]: { ...record.documents[key], received, updatedAt: received ? new Date().toISOString() : null } } }; setRecord(next); void persist(next, received ? '자료 수령을 처리했습니다.' : '자료 수령을 되돌렸습니다.') }
  return <div className="space-y-6">
    <PageHeader title={record.companyName} description="업무, 자료, 수금, 지원사업 준비 상태를 클릭으로 관리합니다." actions={<div className="flex items-center gap-2"><Link to="/ops/clients" className="inline-flex min-h-10 items-center gap-1 px-2 text-sm font-medium text-slate-600"><ArrowLeft className="size-4" />목록</Link><Button onClick={save} disabled={saving}><Save className="size-4" />{saving ? '저장 중...' : '저장'}</Button></div>} />
    {message && <p role="status" className="rounded-(--radius-control) bg-brand-50 px-4 py-3 text-sm text-brand-800">{message}</p>}
    <section className="grid gap-3 md:grid-cols-[1.4fr_1fr]">
      <div className="border border-slate-200 bg-white p-5 shadow-(--shadow-card)"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-slate-500">전체 진행률</p><strong className="mt-1 block text-3xl text-slate-900">{percent}%</strong><p className="mt-1 text-sm text-slate-500">업무 {progress.tasks}/5 · 자료 {progress.documents}/10 · 수금 {progress.payment}/2</p></div><div className="flex size-16 items-center justify-center rounded-full" style={{ background: `conic-gradient(#2563eb ${percent}%, #e2e8f0 0)` }}><span className="flex size-12 items-center justify-center rounded-full bg-white text-sm font-semibold text-slate-800">{percent}%</span></div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand-600 transition-all" style={{ width: `${percent}%` }} /></div></div>
      <div className="border border-slate-200 bg-white p-5 shadow-(--shadow-card)"><p className="text-sm text-slate-500">현재 상태</p><div className="mt-3 grid grid-cols-2 gap-2">{Object.entries(statusLabel).map(([status, label]) => <button key={status} type="button" onClick={() => void persist({ ...record, status: status as OperationsClient['status'] }, `${label} 상태로 변경했습니다.`)} className={`min-h-10 rounded-(--radius-control) border px-2 text-sm font-medium ${record.status === status ? 'border-brand-600 bg-brand-600 text-white' : 'border-slate-200 bg-white text-slate-600 hover:border-brand-300'}`}>{label}</button>)}</div></div>
    </section>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.45fr)_minmax(300px,0.8fr)]">
      <div className="space-y-5">
        <Panel className="overflow-hidden"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold text-slate-900">기본 업무</h2><p className="mt-1 text-sm text-slate-500">완료와 기한을 빠르게 지정합니다.</p></div><ul className="divide-y divide-slate-100">{OPERATIONS_TASKS.map(([key, label]) => <li key={key} className="px-5 py-4"><div className="flex flex-wrap items-center gap-3"><button type="button" onClick={() => taskUpdate(key, { completed: !record.tasks[key].completed }, true)} className={`flex size-7 shrink-0 items-center justify-center rounded-full border ${record.tasks[key].completed ? 'border-brand-600 bg-brand-600 text-white' : 'border-slate-300 text-transparent hover:border-brand-500'}`} aria-label={`${label} 완료 처리`}><Check className="size-4" /></button><strong className={`min-w-35 flex-1 text-sm ${record.tasks[key].completed ? 'text-slate-400 line-through' : 'text-slate-800'}`}>{label}</strong><div className="flex items-center gap-1"><button type="button" onClick={() => taskUpdate(key, { dueDate: dateFromToday(0) }, true)} className="rounded border border-slate-200 px-2 py-1 text-xs text-slate-600 hover:border-brand-300">오늘</button><button type="button" onClick={() => taskUpdate(key, { dueDate: dateFromToday(3) }, true)} className="rounded border border-slate-200 px-2 py-1 text-xs text-slate-600 hover:border-brand-300">3일</button><button type="button" onClick={() => taskUpdate(key, { dueDate: dateFromToday(7) }, true)} className="rounded border border-slate-200 px-2 py-1 text-xs text-slate-600 hover:border-brand-300">1주</button><label className="relative flex size-7 cursor-pointer items-center justify-center rounded border border-slate-200 text-slate-500 hover:border-brand-300" title="직접 날짜 선택"><CalendarDays className="size-4" /><input aria-label={`${label} 기한`} type="date" value={record.tasks[key].dueDate} onChange={(event) => taskUpdate(key, { dueDate: event.target.value }, true)} className="absolute inset-0 cursor-pointer opacity-0" /></label></div></div><div className="mt-2 flex items-center gap-2 pl-10"><span className="text-xs text-slate-400">{record.tasks[key].dueDate ? `기한 ${record.tasks[key].dueDate}` : '기한 미정'}</span><input value={record.tasks[key].note} onChange={(event) => taskUpdate(key, { note: event.target.value })} onBlur={save} placeholder="진행 메모" className="min-w-0 flex-1 border-b border-slate-200 bg-transparent py-1 text-sm outline-none focus:border-brand-500" /></div></li>)}</ul></Panel>
        <Panel className="overflow-hidden"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold text-slate-900">필수 자료</h2><p className="mt-1 text-sm text-slate-500">자료를 받으면 항목을 눌러 즉시 반영합니다.</p></div><ul className="grid divide-y divide-slate-100 sm:grid-cols-2 sm:divide-x">{OPERATIONS_DOCUMENTS.map(([key, label]) => <li key={key} className="flex items-center gap-2 px-4 py-3"><button type="button" onClick={() => documentUpdate(key, !record.documents[key].received)} className={`flex min-h-9 flex-1 items-center gap-2 text-left text-sm ${record.documents[key].received ? 'text-brand-700' : 'text-slate-700'}`}><CircleCheck className={`size-5 shrink-0 ${record.documents[key].received ? 'fill-brand-600 text-white' : 'text-slate-300'}`} /><span className="truncate">{record.documents[key].fileName || label}</span></button>{getDataModeConfig().mode === 'supabase' ? <label title={`${label} 파일 첨부`} className="cursor-pointer text-slate-400 hover:text-brand-600"><FileUp className="size-4" /><input aria-label={`${label} 파일 첨부`} type="file" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) void attach(key, file); event.currentTarget.value = '' }} /></label> : <FileUp className="size-4 text-slate-300" />}</li>)}</ul></Panel>
      </div>
      <div className="space-y-5">
        <Panel className="p-5"><h2 className="font-semibold text-slate-900">다음 할 일</h2><input value={record.nextAction} onChange={(event) => change('nextAction', event.target.value)} onBlur={save} placeholder="다음에 처리할 내용을 적어두세요" className="mt-3 w-full rounded border border-slate-300 px-3 py-2 text-sm" /><div className="mt-2 flex gap-2"><button type="button" onClick={() => void persist({ ...record, nextActionDueDate: dateFromToday(0) })} className="rounded border border-slate-200 px-2 py-1 text-xs">오늘</button><button type="button" onClick={() => void persist({ ...record, nextActionDueDate: dateFromToday(7) })} className="rounded border border-slate-200 px-2 py-1 text-xs">1주</button><input type="date" value={record.nextActionDueDate} onChange={(event) => change('nextActionDueDate', event.target.value)} onBlur={save} className="min-w-0 flex-1 rounded border border-slate-300 px-2 py-1 text-sm" /></div></Panel>
        <Panel className="p-5"><h2 className="font-semibold text-slate-900">계약·수금</h2><div className="mt-3 grid gap-3">{([['contractDepositAmount', '계약금'], ['successFeeAmount', '성공보수']] as const).map(([key, label]) => <label key={key} className="text-xs font-medium text-slate-600">{label}<input type="number" min="0" value={record[key] ?? ''} onChange={(event) => change(key, event.target.value === '' ? null : Number(event.target.value))} onBlur={save} className="mt-1 w-full rounded border border-slate-300 px-3 py-2 text-sm" /></label>)}<button type="button" onClick={() => void persist({ ...record, contractDepositReceived: !record.contractDepositReceived }, record.contractDepositReceived ? '계약금 수령을 되돌렸습니다.' : '계약금 수령을 처리했습니다.')} className={`min-h-10 rounded-(--radius-control) border text-sm font-medium ${record.contractDepositReceived ? 'border-emerald-600 bg-emerald-600 text-white' : 'border-slate-200 text-slate-600'}`}>계약금 {record.contractDepositReceived ? '수령 완료' : '미수령'}</button><button type="button" onClick={() => void persist({ ...record, successFeeReceived: !record.successFeeReceived }, record.successFeeReceived ? '성공보수 수령을 되돌렸습니다.' : '성공보수 수령을 처리했습니다.')} className={`min-h-10 rounded-(--radius-control) border text-sm font-medium ${record.successFeeReceived ? 'border-emerald-600 bg-emerald-600 text-white' : 'border-slate-200 text-slate-600'}`}>성공보수 {record.successFeeReceived ? '수령 완료' : '미수령'}</button></div></Panel>
        <Panel className="p-5"><h2 className="font-semibold text-slate-900">고객 정보</h2><div className="mt-4 grid gap-3">{([['contactName', '담당자'], ['contactPhone', '연락처'], ['contactEmail', '이메일'], ['businessNumber', '사업자등록번호'], ['corporateNumber', '법인번호'], ['businessAddress', '사업장 주소'], ['industry', '업종']] as const).map(([key, label]) => <label key={key} className="text-xs font-medium text-slate-600">{label}<input value={record[key]} onChange={(event) => change(key, event.target.value)} onBlur={save} className="mt-1 w-full rounded border border-slate-300 px-3 py-2 text-sm text-slate-800" /></label>)}</div></Panel>
        <Panel className="p-5"><h2 className="font-semibold text-slate-900">정책자금·지원사업</h2><input value={record.fundingStatus} onChange={(event) => change('fundingStatus', event.target.value)} onBlur={save} placeholder="예: 2026 혁신바우처 검토 중" className="mt-3 w-full rounded border border-slate-300 px-3 py-2 text-sm" /><textarea value={record.fundingNote} onChange={(event) => change('fundingNote', event.target.value)} onBlur={save} placeholder="컨택, 사업계획서, 보완자료 진행 메모" className="mt-2 min-h-24 w-full rounded border border-slate-300 px-3 py-2 text-sm" /></Panel>
      </div>
    </div>
  </div>
}

function CloudClientDetail() { const { currentWorkspaceId } = useAuth(); return <ClientDetailContent workspaceId={currentWorkspaceId} /> }
export function OperationsClientDetailPage() { return getDataModeConfig().mode === 'supabase' ? <CloudClientDetail /> : <ClientDetailContent workspaceId={null} /> }
