import type { ActivityLog, Organization, Project } from '../types/domain'
import { STORAGE_KEYS, readJson, writeJson } from '../storage/localStore'

/**
 * 최초 실행 시 1회만 시드한다.
 * 스키마 버전이 이미 기록되어 있으면 기존 데이터를 절대 덮어쓰지 않는다.
 * 전화번호·이메일·사업자번호는 명백한 데모 형식만 사용한다.
 */

const T0 = '2026-05-11T09:00:00.000Z'
const T1 = '2026-06-02T09:30:00.000Z'
const T2 = '2026-06-24T10:00:00.000Z'
const T3 = '2026-07-13T14:00:00.000Z'

const SEED_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-001',
    name: '대한정밀',
    businessRegistrationNumber: '123-45-67890',
    industry: '정밀가공 제조업',
    subIndustry: '금속 절삭가공',
    businessType: 'corporation',
    foundedAt: '2008-03-14',
    employeeCount: 42,
    annualRevenue: 12_000_000_000,
    region: '경기 시흥',
    address: '경기도 시흥시 공단1대로 000',
    website: 'https://daehan-precision.example.com',
    primaryContact: {
      name: '김도현',
      position: '생산혁신팀장',
      phone: '010-0000-0001',
      email: 'contact@daehan.example.com',
    },
    status: 'active',
    healthStatus: 'healthy',
    notes: '기술보증 연계 의지가 높고 내부 데이터 정리가 잘 되어 있는 고객사.',
    createdAt: T0,
    updatedAt: T3,
    archivedAt: null,
  },
  {
    id: 'org-002',
    name: 'ABC제조',
    businessRegistrationNumber: '234-56-78901',
    industry: '제조업',
    subIndustry: '산업용 부품 조립',
    businessType: 'corporation',
    foundedAt: '2012-09-01',
    employeeCount: 28,
    annualRevenue: 6_500_000_000,
    region: '인천 남동',
    address: '인천광역시 남동구 산업로 000',
    website: 'https://abc-mfg.example.com',
    primaryContact: {
      name: '이정민',
      position: '경영지원실장',
      phone: '010-0000-0002',
      email: 'contact@abcmfg.example.com',
    },
    status: 'active',
    healthStatus: 'healthy',
    notes: '현장자료가 종이·엑셀에 분산되어 있어 통합관리 수요가 큼.',
    createdAt: T0,
    updatedAt: T2,
    archivedAt: null,
  },
  {
    id: 'org-003',
    name: '스마트물류',
    businessRegistrationNumber: '345-67-89012',
    industry: '물류·운송',
    subIndustry: '권역 배송·수거',
    businessType: 'corporation',
    foundedAt: '2016-05-20',
    employeeCount: 35,
    annualRevenue: 4_800_000_000,
    region: '경기 김포',
    address: '경기도 김포시 물류단지로 000',
    website: 'https://smartlogis.example.com',
    primaryContact: {
      name: '박성호',
      position: '운영본부장',
      phone: '010-0000-0003',
      email: 'ops@smartlogis.example.com',
    },
    status: 'active',
    healthStatus: 'attention',
    notes: '워크숍 자료 회신이 지연되는 중. 담당자 일정 확인 필요.',
    createdAt: T1,
    updatedAt: T3,
    archivedAt: null,
  },
  {
    id: 'org-004',
    name: 'C병원',
    businessRegistrationNumber: '456-78-90123',
    industry: '병원·의료지원',
    subIndustry: '전문 재활병원',
    businessType: 'medical',
    foundedAt: '2010-11-08',
    employeeCount: 64,
    annualRevenue: 9_200_000_000,
    region: '서울 강서',
    address: '서울특별시 강서구 의료원길 000',
    website: 'https://c-hospital.example.com',
    primaryContact: {
      name: '최은서',
      position: '기획실 과장',
      phone: '010-0000-0004',
      email: 'plan@chospital.example.com',
    },
    status: 'active',
    healthStatus: 'healthy',
    notes: '환자자료 수집 흐름 개선에 관심. 내부 결재 절차가 다소 긴 편.',
    createdAt: T1,
    updatedAt: T2,
    archivedAt: null,
  },
  {
    id: 'org-005',
    name: '한빛세무사무소',
    businessRegistrationNumber: '567-89-01234',
    industry: '전문서비스',
    subIndustry: '세무·회계',
    businessType: 'sole_proprietor',
    foundedAt: '2014-02-17',
    employeeCount: 9,
    annualRevenue: 1_100_000_000,
    region: '서울 마포',
    address: '서울특별시 마포구 성암로 000',
    website: '',
    primaryContact: {
      name: '한지원',
      position: '대표 세무사',
      phone: '010-0000-0005',
      email: 'hello@hanbit-tax.example.com',
    },
    status: 'paused',
    healthStatus: 'risk',
    notes: '홈페이지 디자인 방향 합의가 지연되어 일정 재조율 필요.',
    createdAt: T2,
    updatedAt: T3,
    archivedAt: null,
  },
  {
    id: 'org-006',
    name: '비원미래',
    businessRegistrationNumber: '678-90-12345',
    industry: '환경·폐기물',
    subIndustry: '의료폐기물 수집·운반',
    businessType: 'corporation',
    foundedAt: '2011-07-04',
    employeeCount: 21,
    annualRevenue: 3_600_000_000,
    region: '충남 천안',
    address: '충청남도 천안시 서북구 환경로 000',
    website: 'https://biwon.example.com',
    primaryContact: {
      name: '정수현',
      position: '운영팀장',
      phone: '010-0000-0006',
      email: 'ops@biwon.example.com',
    },
    status: 'active',
    healthStatus: 'attention',
    notes: '현장검증 2차 준비 중. 차량 기사 교육 일정 조율 필요.',
    createdAt: T2,
    updatedAt: T3,
    archivedAt: null,
  },
]

const SEED_PROJECTS: Project[] = [
  {
    id: 'proj-101',
    projectCode: 'AX-2026-001',
    organizationId: 'org-001',
    name: '생산계획 AX MVP',
    projectType: 'ax',
    objective: '수기 생산계획 수립을 자동 배정으로 전환해 계획 수립 시간을 단축한다.',
    currentStage: 'deliverables',
    currentMvpLevel: 3,
    targetMvpLevel: 4,
    status: 'active',
    healthStatus: 'healthy',
    progress: 85,
    ownerId: 'member-kim',
    fundingRequired: true,
    targetInstitutions: ['기술보증기금', '중소벤처기업진흥공단'],
    targetFundingAmount: 80_000_000,
    startDate: '2026-05-18',
    dueDate: '2026-08-14',
    nextAction: '기관 설명자료 초안 검토',
    nextActionDueDate: '2026-07-20',
    riskSummary: '',
    createdAt: T0,
    updatedAt: T3,
    archivedAt: null,
  },
  {
    id: 'proj-102',
    projectCode: 'WEB-2026-002',
    organizationId: 'org-001',
    name: '기업 홈페이지 리뉴얼',
    projectType: 'website',
    objective: '기술보증·수주 대응을 위한 반응형 기업 홈페이지를 구축한다.',
    currentStage: 'website_design',
    currentMvpLevel: 1,
    targetMvpLevel: 3,
    status: 'planned',
    healthStatus: 'healthy',
    progress: 15,
    ownerId: 'member-choi',
    fundingRequired: false,
    targetInstitutions: [],
    targetFundingAmount: null,
    startDate: '2026-07-06',
    dueDate: '2026-09-11',
    nextAction: '디자인 방향 킥오프 일정 확정',
    nextActionDueDate: '2026-07-27',
    riskSummary: '',
    createdAt: T2,
    updatedAt: T3,
    archivedAt: null,
  },
  {
    id: 'proj-103',
    projectCode: 'AX-2026-003',
    organizationId: 'org-002',
    name: '현장자료 통합관리 MVP',
    projectType: 'ax',
    objective: '종이·엑셀에 분산된 현장자료를 단일 입력 흐름으로 통합한다.',
    currentStage: 'diagnosis',
    currentMvpLevel: 0,
    targetMvpLevel: 2,
    status: 'active',
    healthStatus: 'healthy',
    progress: 65,
    ownerId: 'member-park',
    fundingRequired: false,
    targetInstitutions: [],
    targetFundingAmount: null,
    startDate: '2026-06-08',
    dueDate: '2026-09-25',
    nextAction: '진단 인터뷰 2차 진행',
    nextActionDueDate: '2026-07-21',
    riskSummary: '',
    createdAt: T1,
    updatedAt: T3,
    archivedAt: null,
  },
  {
    id: 'proj-104',
    projectCode: 'HYB-2026-004',
    organizationId: 'org-003',
    name: '배차·수거 일정 자동화',
    projectType: 'ax_website',
    objective: '배차·수거 일정 수립을 자동화하고 고객 안내용 홈페이지를 함께 구축한다.',
    currentStage: 'selection',
    currentMvpLevel: 1,
    targetMvpLevel: 3,
    status: 'waiting_client',
    healthStatus: 'attention',
    progress: 40,
    ownerId: 'member-park',
    fundingRequired: true,
    targetInstitutions: ['신용보증기금', '지자체 지원사업'],
    targetFundingAmount: 50_000_000,
    startDate: '2026-06-15',
    dueDate: '2026-10-16',
    nextAction: '과제선별 워크숍 자료 회신 대기',
    nextActionDueDate: '2026-07-22',
    riskSummary: '현장 데이터 표본이 부족해 선별 지표 신뢰도가 낮을 수 있음.',
    createdAt: T1,
    updatedAt: T3,
    archivedAt: null,
  },
  {
    id: 'proj-105',
    projectCode: 'AX-2026-005',
    organizationId: 'org-004',
    name: '환자자료 수집 MVP',
    projectType: 'ax',
    objective: '접수·상담 단계의 환자자료 수집을 표준화해 재입력을 제거한다.',
    currentStage: 'mvp_design',
    currentMvpLevel: 2,
    targetMvpLevel: 3,
    status: 'active',
    healthStatus: 'healthy',
    progress: 70,
    ownerId: 'member-choi',
    fundingRequired: false,
    targetInstitutions: [],
    targetFundingAmount: null,
    startDate: '2026-06-10',
    dueDate: '2026-09-04',
    nextAction: 'MVP 설계 검토 회의',
    nextActionDueDate: '2026-07-23',
    riskSummary: '',
    createdAt: T1,
    updatedAt: T2,
    archivedAt: null,
  },
  {
    id: 'proj-106',
    projectCode: 'WEB-2026-006',
    organizationId: 'org-005',
    name: '기업 홈페이지 리뉴얼',
    projectType: 'website',
    objective: '신뢰감 있는 세무사무소 홈페이지로 상담 문의 전환율을 높인다.',
    currentStage: 'website_design',
    currentMvpLevel: 1,
    targetMvpLevel: 3,
    status: 'on_hold',
    healthStatus: 'risk',
    progress: 25,
    ownerId: 'member-choi',
    fundingRequired: false,
    targetInstitutions: [],
    targetFundingAmount: null,
    startDate: '2026-06-29',
    dueDate: '2026-08-28',
    nextAction: '디자인 방향 확정 미팅 재조율',
    nextActionDueDate: '2026-07-17',
    riskSummary: '디자인 방향 합의 지연으로 일정 전체가 밀리는 중.',
    createdAt: T2,
    updatedAt: T3,
    archivedAt: null,
  },
  {
    id: 'proj-107',
    projectCode: 'AX-2026-007',
    organizationId: 'org-006',
    name: '의료폐기물 운영관리 MVP',
    projectType: 'ax',
    objective: '수거 차량 운행·처리 기록을 디지털화해 보고 자료 작성을 자동화한다.',
    currentStage: 'validation',
    currentMvpLevel: 3,
    targetMvpLevel: 4,
    status: 'active',
    healthStatus: 'attention',
    progress: 55,
    ownerId: 'member-lee',
    fundingRequired: true,
    targetInstitutions: ['기술보증기금'],
    targetFundingAmount: 60_000_000,
    startDate: '2026-06-22',
    dueDate: '2026-10-02',
    nextAction: '현장검증 2차 준비',
    nextActionDueDate: '2026-07-24',
    riskSummary: '차량 기사 교육 일정이 확정되지 않음.',
    createdAt: T2,
    updatedAt: T3,
    archivedAt: null,
  },
]

function seedActivity(
  id: string,
  organizationId: string,
  projectId: string | null,
  activityType: ActivityLog['activityType'],
  title: string,
  actorName: string,
  createdAt: string,
): ActivityLog {
  return {
    id,
    organizationId,
    projectId,
    activityType,
    title,
    description: '',
    actorName,
    createdAt,
  }
}

const SEED_ACTIVITIES: ActivityLog[] = [
  ...SEED_ORGANIZATIONS.map((org, index) =>
    seedActivity(
      `act-org-${org.id}`,
      org.id,
      null,
      'organization_created',
      '고객사가 등록되었습니다.',
      index % 2 === 0 ? '김팀장' : '박지훈',
      org.createdAt,
    ),
  ),
  ...SEED_PROJECTS.map((project) =>
    seedActivity(
      `act-proj-${project.id}`,
      project.organizationId,
      project.id,
      'project_created',
      `${project.name} 프로젝트가 생성되었습니다.`,
      '김팀장',
      project.createdAt,
    ),
  ),
  seedActivity(
    'act-extra-1',
    'org-003',
    'proj-104',
    'status_changed',
    '프로젝트 상태가 고객 응답 대기로 변경되었습니다.',
    '박지훈',
    T3,
  ),
  seedActivity(
    'act-extra-2',
    'org-001',
    null,
    'organization_updated',
    '고객사 연락처가 수정되었습니다.',
    '김팀장',
    T3,
  ),
]

/**
 * 스키마 v1 마이그레이션 — 고객사·프로젝트·활동 이력 시드.
 * 기존 데이터가 있으면 덮어쓰지 않는다.
 */
export function seedCoreData(): void {
  const existing = readJson<unknown[]>(STORAGE_KEYS.organizations, [])
  if (Array.isArray(existing) && existing.length > 0) return
  writeJson(STORAGE_KEYS.organizations, SEED_ORGANIZATIONS)
  writeJson(STORAGE_KEYS.projects, SEED_PROJECTS)
  writeJson(STORAGE_KEYS.activities, SEED_ACTIVITIES)
}
