import type {
  AutomationCandidate,
  AutomationCandidateInput,
  CandidateFilters,
  SelectionDecision,
  SelectionDecisionInput,
  SelectionFilters,
  SelectionHandoffInput,
  SelectionHandoffSnapshot,
} from '../types/selection'
import { normalizeQuery } from '../lib/format'
import {
  STORAGE_KEYS,
  generateId,
  notifyStoreChanged,
  readJson,
  writeJson,
} from '../storage/localStore'
import {
  EntityNotFoundError,
  type AutomationCandidateRepository,
  type SelectionDecisionRepository,
  type SelectionHandoffRepository,
} from './types'

function nowIso(): string {
  return new Date().toISOString()
}
function readList<T>(key: string): T[] {
  const value = readJson<T[]>(key, [])
  return Array.isArray(value) ? value : []
}

/* ------------------------------------------------------------------ */
/* 자동화 후보                                                          */
/* ------------------------------------------------------------------ */

export class LocalAutomationCandidateRepository
  implements AutomationCandidateRepository
{
  private read(): AutomationCandidate[] {
    return readList<AutomationCandidate>(STORAGE_KEYS.automationCandidates)
  }
  private write(list: AutomationCandidate[]): void {
    writeJson(STORAGE_KEYS.automationCandidates, list)
    notifyStoreChanged()
  }

  getAll(): AutomationCandidate[] {
    return this.read()
  }
  getById(id: string): AutomationCandidate | null {
    return this.read().find((c) => c.id === id) ?? null
  }
  getByProjectId(projectId: string, includeArchived = false): AutomationCandidate[] {
    return this.read().filter(
      (c) =>
        c.projectId === projectId &&
        (includeArchived || c.status !== 'archived') &&
        (includeArchived || c.archivedAt === null),
    )
  }

  create(input: AutomationCandidateInput): AutomationCandidate {
    const ts = nowIso()
    const candidate: AutomationCandidate = {
      ...input,
      id: generateId(),
      createdAt: ts,
      updatedAt: ts,
      archivedAt: null,
    }
    this.write([...this.read(), candidate])
    return candidate
  }

  createMany(inputs: AutomationCandidateInput[]): AutomationCandidate[] {
    const ts = nowIso()
    const created: AutomationCandidate[] = inputs.map((input) => ({
      ...input,
      id: generateId(),
      createdAt: ts,
      updatedAt: ts,
      archivedAt: null,
    }))
    this.write([...this.read(), ...created])
    return created
  }

  update(id: string, input: Partial<AutomationCandidateInput>): AutomationCandidate {
    const list = this.read()
    const index = list.findIndex((c) => c.id === id)
    if (index < 0) throw new EntityNotFoundError('자동화 후보')
    const updated: AutomationCandidate = {
      ...list[index],
      ...input,
      id,
      updatedAt: nowIso(),
    }
    list[index] = updated
    this.write(list)
    return updated
  }

  archive(id: string): AutomationCandidate {
    return this.update(id, { status: 'archived' } as Partial<AutomationCandidateInput>)
  }

  merge(sourceCandidateIds: string[], target: AutomationCandidate): AutomationCandidate {
    const list = this.read()
    const ts = nowIso()
    // 원본 후보는 물리 삭제하지 않고 보관 처리(이력 보존)
    const next = list.map((c) => {
      if (sourceCandidateIds.includes(c.id) && c.id !== target.id) {
        return { ...c, status: 'archived' as const, archivedAt: ts, updatedAt: ts }
      }
      if (c.id === target.id) {
        return { ...target, updatedAt: ts }
      }
      return c
    })
    this.write(next)
    return next.find((c) => c.id === target.id) as AutomationCandidate
  }

  /**
   * 자동 후보만 새 추출 결과로 교체한다.
   * - 수동 후보 보존
   * - 선정(primary/secondary)·보류·제외된 자동 후보 보존
   * - 담당자가 수정한 자동 후보 보존(수정 표시 없이 무조건 삭제하지 않음)
   * - 그 외 순수 자동 후보(discovered/reviewing 미수정)만 교체
   * - 동일 generationKey면 기존 ID를 유지
   */
  replaceAutoGenerated(
    projectId: string,
    assessmentId: string,
    candidates: AutomationCandidateInput[],
  ): AutomationCandidate[] {
    const ts = nowIso()
    const existing = this.read()
    const preservedStatuses = new Set([
      'shortlisted',
      'selected_primary',
      'selected_secondary',
      'deferred',
      'rejected',
      'archived',
    ])
    const kept = existing.filter((c) => {
      if (c.projectId !== projectId) return true
      if (!c.autoGenerated) return true // 수동 후보 보존
      if (preservedStatuses.has(c.status)) return true // 처리된 후보 보존
      return false // discovered/reviewing 자동 후보만 제거
    })
    // 보존 후보의 generationKey → ID (재생성 시 ID 유지)
    const keptKeyToId = new Map<string, string>()
    kept
      .filter((c) => c.projectId === projectId && c.autoGenerated)
      .forEach((c) => keptKeyToId.set(c.generationKey, c.id))
    const keptKeys = new Set(keptKeyToId.keys())

    const fresh: AutomationCandidate[] = candidates
      .filter((input) => !keptKeys.has(input.generationKey))
      .map((input) => ({
        ...input,
        assessmentId,
        id: generateId(),
        createdAt: ts,
        updatedAt: ts,
        archivedAt: null,
      }))
    this.write([...kept, ...fresh])
    return this.getByProjectId(projectId)
  }

  search(projectId: string, filters: CandidateFilters): AutomationCandidate[] {
    const query = normalizeQuery(filters.query ?? '')
    return this.getByProjectId(projectId, filters.includeArchived).filter((c) => {
      if (filters.status && c.status !== filters.status) return false
      if (filters.taskFamily && c.taskFamily !== filters.taskFamily) return false
      if (filters.automationApproach && c.automationApproach !== filters.automationApproach) return false
      if (filters.aiNecessity && c.aiNecessity !== filters.aiNecessity) return false
      if (filters.complexity && c.complexity !== filters.complexity) return false
      if (filters.quadrant && c.quadrant !== filters.quadrant) return false
      if (filters.confidence && c.confidence !== filters.confidence) return false
      if (filters.autoOnly && !c.autoGenerated) return false
      if (filters.manualOnly && c.autoGenerated) return false
      if (filters.minScore !== undefined && c.priorityScore < filters.minScore) return false
      if (query) {
        const haystack = [
          c.name,
          c.problemStatement,
          c.currentProcess,
          c.users,
          c.inputData,
          c.outputResult,
          ...c.sourceQuestionCodes,
        ]
          .join(' ')
          .toLowerCase()
        if (!haystack.includes(query)) return false
      }
      return true
    })
  }
}

/* ------------------------------------------------------------------ */
/* 선정 결과                                                            */
/* ------------------------------------------------------------------ */

export class LocalSelectionDecisionRepository
  implements SelectionDecisionRepository
{
  private read(): SelectionDecision[] {
    return readList<SelectionDecision>(STORAGE_KEYS.selectionDecisions)
  }
  private write(list: SelectionDecision[]): void {
    writeJson(STORAGE_KEYS.selectionDecisions, list)
    notifyStoreChanged()
  }

  getAll(): SelectionDecision[] {
    return this.read()
  }
  getById(id: string): SelectionDecision | null {
    return this.read().find((d) => d.id === id) ?? null
  }
  getByProjectId(projectId: string): SelectionDecision[] {
    return this.read()
      .filter((d) => d.projectId === projectId)
      .sort((a, b) => b.version - a.version)
  }
  getLatestByProjectId(projectId: string): SelectionDecision | null {
    const list = this.getByProjectId(projectId)
    if (list.length === 0) return null
    return list.find((d) => d.status !== 'superseded') ?? list[0]
  }
  nextVersion(projectId: string): number {
    return this.getByProjectId(projectId).reduce((m, d) => Math.max(m, d.version), 0) + 1
  }

  create(input: SelectionDecisionInput): SelectionDecision {
    const ts = nowIso()
    const decision: SelectionDecision = {
      ...input,
      id: generateId(),
      version: this.nextVersion(input.projectId),
      createdAt: ts,
      updatedAt: ts,
    }
    this.write([...this.read(), decision])
    return decision
  }

  update(id: string, input: Partial<SelectionDecisionInput>): SelectionDecision {
    const list = this.read()
    const index = list.findIndex((d) => d.id === id)
    if (index < 0) throw new EntityNotFoundError('선정 결과')
    const updated: SelectionDecision = {
      ...list[index],
      ...input,
      id,
      version: list[index].version,
      updatedAt: nowIso(),
    }
    list[index] = updated
    this.write(list)
    return updated
  }

  markReviewed(id: string, reviewerName: string): SelectionDecision {
    return this.update(id, { status: 'reviewed', reviewedBy: reviewerName, reviewedAt: nowIso() })
  }

  finalize(id: string, finalizerName: string): SelectionDecision {
    const target = this.getById(id)
    if (!target) throw new EntityNotFoundError('선정 결과')
    const ts = nowIso()
    const next = this.read().map((d) => {
      if (d.projectId === target.projectId && d.id !== id && d.status === 'finalized') {
        return { ...d, status: 'superseded' as const, supersededAt: ts, updatedAt: ts }
      }
      if (d.id === id) {
        return { ...d, status: 'finalized' as const, finalizedBy: finalizerName, finalizedAt: ts, updatedAt: ts }
      }
      return d
    })
    this.write(next)
    return next.find((d) => d.id === id) as SelectionDecision
  }

  supersede(id: string): SelectionDecision {
    return this.update(id, { status: 'superseded', supersededAt: nowIso() })
  }

  search(filters: SelectionFilters): SelectionDecision[] {
    const query = normalizeQuery(filters.query ?? '')
    return this.read().filter((d) => {
      if (filters.status && d.status !== filters.status) return false
      if (query) {
        const haystack = `${d.decisionSummary} ${d.autoSummary}`.toLowerCase()
        if (!haystack.includes(query)) return false
      }
      return true
    })
  }
}

/* ------------------------------------------------------------------ */
/* 인계 스냅샷                                                          */
/* ------------------------------------------------------------------ */

export class LocalSelectionHandoffRepository
  implements SelectionHandoffRepository
{
  private read(): SelectionHandoffSnapshot[] {
    return readList<SelectionHandoffSnapshot>(STORAGE_KEYS.selectionHandoffs)
  }
  private write(list: SelectionHandoffSnapshot[]): void {
    writeJson(STORAGE_KEYS.selectionHandoffs, list)
    notifyStoreChanged()
  }

  getAll(): SelectionHandoffSnapshot[] {
    return this.read()
  }
  getByProjectId(projectId: string): SelectionHandoffSnapshot[] {
    return this.read().filter((h) => h.projectId === projectId)
  }
  getBySelectionDecisionId(selectionDecisionId: string): SelectionHandoffSnapshot | null {
    return this.read().find((h) => h.selectionDecisionId === selectionDecisionId) ?? null
  }

  create(snapshot: SelectionHandoffInput): SelectionHandoffSnapshot {
    const created: SelectionHandoffSnapshot = { ...snapshot, id: generateId() }
    this.write([...this.read(), created])
    return created
  }

  replaceForDecision(
    selectionDecisionId: string,
    snapshot: SelectionHandoffInput,
  ): SelectionHandoffSnapshot {
    const kept = this.read().filter((h) => h.selectionDecisionId !== selectionDecisionId)
    const created: SelectionHandoffSnapshot = { ...snapshot, id: generateId() }
    this.write([...kept, created])
    return created
  }
}
