/**
 * 워크스페이스 범위 Supabase 도메인 저장소(제네릭).
 *
 * 하이브리드 저장(관계 컬럼 + payload jsonb) 테이블에 대해 공통 CRUD 계약을
 * 실제 비동기로 구현한다. 모든 접근은 anon key + RLS 로 보호되고 workspace_id 로
 * 이중 제한된다(service_role 미사용).
 *
 * 각 도메인 인터페이스의 공통 메서드(getAll/getById/create/update/archive/search/
 * getByProjectId/getLatestByProjectId/nextVersion/getByToken 등)를 규약으로 처리하고,
 * 도메인 특화 메서드(merge, replaceAutoGenerated 등)는 아직 어댑터에서 구현되지 않아
 * 호출 시 명시적 오류를 던진다(가짜 성공 금지). 도메인 화면 연결(다음 단계)에서 채운다.
 */

import type { SupabaseClient } from '@supabase/supabase-js'
import { SupabaseTableAdapter, SupabaseRepositoryError } from '../async/supabaseTableAdapter'
import type { PromotedColumns } from '../async/mappers'
import { sha256Hex } from '../async/publicTokenClient'

export interface EntityLike {
  id: string
  createdAt?: string
  updatedAt?: string
  archivedAt?: string | null
  version?: number
  status?: string
  [key: string]: unknown
}

export interface DomainRepoConfig<T extends EntityLike> {
  client: SupabaseClient
  workspaceId: string
  table: string
  /** 엔티티 → 승격(스네이크) 컬럼 값 */
  promote?: (entity: T) => PromotedColumns
  /** search(filters) 구현 */
  searchPredicate?: (entity: T, filters: Record<string, unknown>) => boolean
}

export function nowIso(): string {
  return new Date().toISOString()
}

export function newId(): string {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID()
  }
  return `id-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`
}

/**
 * 공통 저장소 동작을 담은 베이스. 도메인 저장소는 이를 구성해 인터페이스를 만족시킨다.
 */
export class SupabaseDomainRepo<T extends EntityLike> {
  readonly adapter: SupabaseTableAdapter<T>
  readonly table: string
  private readonly config: DomainRepoConfig<T>

  constructor(config: DomainRepoConfig<T>) {
    this.config = config
    this.table = config.table
    this.adapter = new SupabaseTableAdapter<T>({
      client: config.client,
      table: config.table,
      workspaceId: config.workspaceId,
      promote: config.promote,
    })
  }

  async getAll(includeArchived = false): Promise<T[]> {
    const rows = await this.adapter.list()
    return includeArchived ? rows : rows.filter((r) => (r.archivedAt ?? null) === null)
  }

  getById(id: string): Promise<T | null> {
    return this.adapter.getById(id)
  }

  async getByColumn(column: string, value: string): Promise<T[]> {
    return this.adapter.listWhere(column, value)
  }

  async getByProjectId(projectId: string): Promise<T[]> {
    const rows = await this.adapter.listWhere('project_id', projectId)
    return rows
  }

  async getByOrganizationId(organizationId: string, includeArchived = false): Promise<T[]> {
    const rows = await this.adapter.listWhere('organization_id', organizationId)
    return includeArchived ? rows : rows.filter((r) => (r.archivedAt ?? null) === null)
  }

  async getByInstitutionId(institutionId: string): Promise<T[]> {
    return this.adapter.listWhere('institution_id', institutionId)
  }

  /** superseded 가 아닌 최신 버전(없으면 최신) */
  async getLatestByProjectId(projectId: string): Promise<T | null> {
    const rows = await this.getByProjectId(projectId)
    if (rows.length === 0) return null
    const active = rows.filter((r) => r.status !== 'superseded')
    const pool = active.length > 0 ? active : rows
    return pool.reduce((a, b) => ((b.version ?? 0) > (a.version ?? 0) ? b : a))
  }

  async nextVersion(projectId: string): Promise<number> {
    const rows = await this.getByProjectId(projectId)
    return rows.reduce((max, r) => Math.max(max, r.version ?? 0), 0) + 1
  }

  /** 공개 토큰(원문)으로 조회 — 서버 저장은 해시. 여기서도 해시로 비교한다. */
  async getByToken(rawToken: string): Promise<T | null> {
    const hash = await sha256Hex(rawToken)
    const rows = await this.adapter.listWhere('access_token_hash', hash)
    return rows[0] ?? null
  }

  async create(input: Partial<T>): Promise<T> {
    const ts = nowIso()
    const entity = {
      ...input,
      id: newId(),
      createdAt: ts,
      updatedAt: ts,
      archivedAt: (input as { archivedAt?: string | null }).archivedAt ?? null,
    } as unknown as T
    return this.adapter.insert(entity)
  }

  async update(id: string, input: Partial<T>): Promise<T> {
    const existing = await this.adapter.getById(id)
    if (!existing) throw new SupabaseRepositoryError(`${this.table} 항목을 찾을 수 없습니다.`)
    const merged = { ...existing, ...input, id, updatedAt: nowIso() } as T
    return this.adapter.update(merged)
  }

  async archive(id: string): Promise<T> {
    const existing = await this.adapter.getById(id)
    if (!existing) throw new SupabaseRepositoryError(`${this.table} 항목을 찾을 수 없습니다.`)
    const ts = nowIso()
    const merged = { ...existing, status: 'archived', archivedAt: ts, updatedAt: ts } as T
    return this.adapter.update(merged)
  }

  async search(filters: Record<string, unknown>): Promise<T[]> {
    const includeArchived = Boolean((filters as { includeArchived?: boolean }).includeArchived)
    const rows = await this.getAll(includeArchived)
    if (!this.config.searchPredicate) return rows
    return rows.filter((r) => this.config.searchPredicate!(r, filters))
  }

  async removeById(id: string): Promise<void> {
    return this.adapter.remove(id)
  }
}

/** 아직 Supabase 에서 구현되지 않은 도메인 특화 메서드용 명시적 오류 thunk. */
export function notImplemented(repo: string, method: string): (...args: unknown[]) => Promise<never> {
  return () =>
    Promise.reject(
      new SupabaseRepositoryError(
        `${repo}.${method} 은(는) 아직 Supabase 어댑터에서 구현되지 않았습니다(다음 단계에서 도메인 화면 연결 시 구현).`,
      ),
    )
}
