/**
 * 워크스페이스 범위 jsonb 도메인 테이블에 대한 제네릭 Supabase 어댑터.
 *
 * 하이브리드 저장(관계 컬럼 + payload jsonb) 테이블의 공통 CRUD 를 담당한다.
 * 도메인별 특수 메서드(nextVersion, replaceAutoGenerated, merge 등)는 이 어댑터를
 * 조합해 상위(도메인 어댑터)에서 구현한다.
 *
 * 모든 접근은 anon key + RLS 로 보호된다. 이 모듈은 UI 가 직접 사용하지 않으며
 * Repository 계층에서만 쓴다. service_role 키에 의존하지 않는다.
 */

import type { SupabaseClient } from '@supabase/supabase-js'
import { rowToEntity, entityToRow, type DomainRow, type EntityLike, type PromotedColumns } from './mappers'

export class SupabaseRepositoryError extends Error {
  readonly reason?: unknown

  constructor(message: string, reason?: unknown) {
    super(message)
    this.name = 'SupabaseRepositoryError'
    this.reason = reason
  }
}

export interface TableAdapterOptions<T extends EntityLike> {
  client: SupabaseClient
  table: string
  workspaceId: string
  /** 엔티티 → 승격(스네이크) 컬럼 값 */
  promote?: (entity: T) => PromotedColumns
}

/**
 * 제네릭 도메인 테이블 어댑터.
 * 항상 workspace_id 로 범위를 제한하고(RLS 이중 방어), payload 를 엔티티로 복원한다.
 */
export class SupabaseTableAdapter<T extends EntityLike> {
  private readonly client: SupabaseClient
  private readonly table: string
  private readonly workspaceId: string
  private readonly promote?: (entity: T) => PromotedColumns

  constructor(options: TableAdapterOptions<T>) {
    this.client = options.client
    this.table = options.table
    this.workspaceId = options.workspaceId
    this.promote = options.promote
  }

  private fail(action: string, error: unknown): never {
    throw new SupabaseRepositoryError(`${this.table} ${action} 중 오류가 발생했습니다.`, error)
  }

  async list(): Promise<T[]> {
    const { data, error } = await this.client
      .from(this.table)
      .select('*')
      .eq('workspace_id', this.workspaceId)
      .order('created_at', { ascending: true })
    if (error) this.fail('목록 조회', error)
    return (data ?? []).map((row) => rowToEntity<T>(row as DomainRow))
  }

  async listWhere(column: string, value: string | number | boolean): Promise<T[]> {
    const { data, error } = await this.client
      .from(this.table)
      .select('*')
      .eq('workspace_id', this.workspaceId)
      .eq(column, value)
      .order('created_at', { ascending: true })
    if (error) this.fail('조건 조회', error)
    return (data ?? []).map((row) => rowToEntity<T>(row as DomainRow))
  }

  async getById(id: string): Promise<T | null> {
    const { data, error } = await this.client
      .from(this.table)
      .select('*')
      .eq('workspace_id', this.workspaceId)
      .eq('id', id)
      .maybeSingle()
    if (error) this.fail('단건 조회', error)
    return data ? rowToEntity<T>(data as DomainRow) : null
  }

  async insert(entity: T): Promise<T> {
    const row = entityToRow<T>(entity, this.workspaceId, this.promote)
    const { data, error } = await this.client
      .from(this.table)
      .insert(row)
      .select('*')
      .single()
    if (error) this.fail('생성', error)
    return rowToEntity<T>(data as DomainRow)
  }

  async upsert(entity: T): Promise<T> {
    const row = entityToRow<T>(entity, this.workspaceId, this.promote)
    const { data, error } = await this.client
      .from(this.table)
      .upsert(row)
      .select('*')
      .single()
    if (error) this.fail('저장', error)
    return rowToEntity<T>(data as DomainRow)
  }

  async update(entity: T): Promise<T> {
    const row = entityToRow<T>(entity, this.workspaceId, this.promote)
    const { data, error } = await this.client
      .from(this.table)
      .update(row)
      .eq('workspace_id', this.workspaceId)
      .eq('id', entity.id)
      .select('*')
      .single()
    if (error) this.fail('수정', error)
    return rowToEntity<T>(data as DomainRow)
  }

  async remove(id: string): Promise<void> {
    const { error } = await this.client
      .from(this.table)
      .delete()
      .eq('workspace_id', this.workspaceId)
      .eq('id', id)
    if (error) this.fail('삭제', error)
  }
}
