import type {
  AnalysisIssueInput,
  AnalysisIssueSeverity,
  AnalysisIssueType,
  DomainScore,
  ResponseComparisonItem,
} from '../../types/assessment'
import { RESPONDENT_ROLE_META } from '../../lib/surveyMeta'
import { evidenceId } from './evidenceBuilder'
import { TAG } from './scoringConfig'
import { answerForRoleTag, answersForTag, type AnalysisDataset } from './analysisData'

const SEVERITY_ORDER: Record<AnalysisIssueSeverity, number> = {
  critical: 0,
  warning: 1,
  info: 2,
}

interface DraftIssue {
  ruleKey: string
  type: AnalysisIssueType
  severity: AnalysisIssueSeverity
  title: string
  description: string
  relatedQuestionCodes: string[]
  relatedResponseIds: string[]
  evidenceIds: string[]
  suggestedAction: string
}

function toInput(projectId: string, draft: DraftIssue): AnalysisIssueInput {
  return {
    projectId,
    type: draft.type,
    severity: draft.severity,
    title: draft.title,
    description: draft.description,
    relatedQuestionIds: draft.relatedQuestionCodes.map((c) => `q-${c}`),
    relatedResponseIds: draft.relatedResponseIds,
    evidenceIds: draft.evidenceIds,
    suggestedAction: draft.suggestedAction,
    status: 'open',
    resolutionNote: '',
    resolvedAt: null,
    ruleKey: draft.ruleKey,
    autoGenerated: true,
  }
}

function conflictEvidenceIds(item: ResponseComparisonItem): string[] {
  return item.respondentValues.flatMap((v) =>
    item.relatedQuestionCodes.map((code) => evidenceId(v.responseId, code)),
  )
}

/** 비교 결과에서 모순·인식 차이 이슈 생성 */
function conflictIssues(
  comparisons: ResponseComparisonItem[],
): DraftIssue[] {
  const out: DraftIssue[] = []
  for (const item of comparisons) {
    if (item.status !== 'major_gap' && item.status !== 'minor_gap') continue
    const isMajor = item.status === 'major_gap'
    const roleValues = item.respondentValues
      .map(
        (v) =>
          `${RESPONDENT_ROLE_META[v.role].label} "${v.displayValue}"`,
      )
      .join(' vs ')

    if (item.topicKey === 'usage_will') {
      if (!isMajor) continue
      out.push({
        ruleKey: 'conflict_usage_will',
        type: 'perception_gap',
        severity: 'critical',
        title: '대표자·현장 사용 의지 충돌',
        description: `사용 의지 응답이 크게 다릅니다. ${roleValues}. 실제 사용 주체의 의지 확인이 필요합니다.`,
        relatedQuestionCodes: item.relatedQuestionCodes,
        relatedResponseIds: item.respondentValues.map((v) => v.responseId),
        evidenceIds: conflictEvidenceIds(item),
        suggestedAction: '실제 사용 담당자와 사용 의지·참여 가능 시간을 확인하세요.',
      })
    } else if (item.topicKey === 'monthly_workload') {
      out.push({
        ruleKey: 'conflict_workload',
        type: 'contradiction',
        severity: isMajor ? 'critical' : 'warning',
        title: '업무량 인식 차이',
        description: `월 업무량 응답에 차이가 있습니다. ${roleValues}. 산정 기준 확인이 필요합니다.`,
        relatedQuestionCodes: item.relatedQuestionCodes,
        relatedResponseIds: item.respondentValues.map((v) => v.responseId),
        evidenceIds: conflictEvidenceIds(item),
        suggestedAction: '업무 범위와 산정 기준을 인터뷰로 확인하세요.',
      })
    } else if (item.topicKey === 'data_holding') {
      if (!isMajor) continue
      out.push({
        ruleKey: 'conflict_data_holding',
        type: 'contradiction',
        severity: 'warning',
        title: '데이터 보유 상태 인식 차이',
        description: `데이터 보관 형태 응답이 응답자마다 다릅니다. ${roleValues}.`,
        relatedQuestionCodes: item.relatedQuestionCodes,
        relatedResponseIds: item.respondentValues.map((v) => v.responseId),
        evidenceIds: conflictEvidenceIds(item),
        suggestedAction: '실제 데이터 샘플을 확인해 보유 형태를 검증하세요.',
      })
    } else if (item.topicKey === 'test_owner' || item.topicKey === 'data_provision') {
      if (!isMajor) continue
      out.push({
        ruleKey: `conflict_${item.topicKey}`,
        type: 'contradiction',
        severity: 'warning',
        title: `${item.title} 응답 충돌`,
        description: `${item.title}에 대한 응답이 다릅니다. ${roleValues}.`,
        relatedQuestionCodes: item.relatedQuestionCodes,
        relatedResponseIds: item.respondentValues.map((v) => v.responseId),
        evidenceIds: conflictEvidenceIds(item),
        suggestedAction: '실제 실행 담당자와 참여·제공 가능 여부를 재확인하세요.',
      })
    }
  }
  return out
}

/** 누락·부족 이슈 */
function missingDataIssues(dataset: AnalysisDataset): DraftIssue[] {
  const out: DraftIssue[] = []
  const isWebsite = dataset.project.projectType === 'website'
  if (isWebsite) return out

  const anyAnswered = (tag: string) =>
    answersForTag(dataset, tag).length > 0

  // KPI 누락: 개선 목표는 있으나 측정 지표 없음
  const kpiAnswers = answersForTag(dataset, TAG.measurableKpi)
  const goalAnswered = anyAnswered(TAG.improvementGoal)
  const kpiNone =
    kpiAnswers.length === 0 ||
    kpiAnswers.every((a) =>
      a.normalized.selectedOptionValues.includes('none'),
    )
  if (goalAnswered && kpiNone) {
    out.push({
      ruleKey: 'missing_kpi',
      type: 'missing_data',
      severity: 'warning',
      title: '측정 가능한 KPI 없음',
      description:
        '개선 목표는 있으나 개선 전후를 비교할 측정 지표가 확인되지 않았습니다.',
      relatedQuestionCodes: ['COM-KPI-005', 'COM-KPI-004'],
      relatedResponseIds: [],
      evidenceIds: [],
      suggestedAction: '현재 건당 처리시간·월 처리건수·오류 건수 중 측정 가능한 항목을 확인하세요.',
    })
  }

  // 업무량 수치 데이터 없음
  const hasWorkloadNumbers =
    anyAnswered(TAG.baselineTime) || anyAnswered(TAG.taskInventory)
  if (!hasWorkloadNumbers) {
    out.push({
      ruleKey: 'missing_workload',
      type: 'missing_data',
      severity: 'warning',
      title: '업무량 데이터 부족',
      description:
        '월 업무시간·반복업무 표 등 업무량을 판단할 수 있는 수치 데이터가 부족합니다.',
      relatedQuestionCodes: ['COM-KPI-001', 'COM-WF-001'],
      relatedResponseIds: [],
      evidenceIds: [],
      suggestedAction: '반복 업무 목록과 월 처리량·소요시간을 인터뷰로 확인하세요.',
    })
  }

  // 데이터 제공 가능성 미확인
  if (!anyAnswered(TAG.dataProvision)) {
    out.push({
      ruleKey: 'missing_data_provision',
      type: 'missing_data',
      severity: 'info',
      title: '자료 제공 가능성 미확인',
      description: '진단·구축용 실제 자료 제공 가능 여부가 확인되지 않았습니다.',
      relatedQuestionCodes: ['COM-AD-004'],
      relatedResponseIds: [],
      evidenceIds: [],
      suggestedAction: '실제 업무 자료 샘플 제공 가능 여부를 확인하세요.',
    })
  }

  return out
}

/** 위험 신호·전문가 검토 이슈 */
function riskIssues(dataset: AnalysisDataset): DraftIssue[] {
  const out: DraftIssue[] = []

  // 개인정보 처리
  const privacy = answersForTag(dataset, TAG.privacy).filter((a) =>
    ['yes'].includes(String(a.normalized.rawValue)),
  )
  if (privacy.length > 0) {
    out.push({
      ruleKey: 'risk_privacy',
      type: 'risk_signal',
      severity: 'warning',
      title: '개인정보·민감정보 처리',
      description:
        '개인정보 또는 민감정보를 다루는 업무가 있어 처리 범위·주체 확인과 법적 검토가 필요할 수 있습니다.',
      relatedQuestionCodes: ['COM-DATA-006'],
      relatedResponseIds: privacy.map((a) => a.respondent.responseId),
      evidenceIds: privacy.map((a) =>
        evidenceId(a.respondent.responseId, a.normalized.questionCode),
      ),
      suggestedAction: '개인정보 처리 주체·범위를 확인하고 필요 시 전문가 검토를 진행하세요.',
    })
  }

  // 전문가 최종 판단 필요 (사람 검토)
  const humanReview = answersForTag(dataset, TAG.humanReview).filter((a) =>
    ['yes'].includes(String(a.normalized.rawValue)),
  )
  if (humanReview.length > 0) {
    out.push({
      ruleKey: 'expert_human_review',
      type: 'expert_review',
      severity: 'warning',
      title: '전문가 최종 검토 필요 업무',
      description:
        '결과에 대한 사람의 최종 검토가 필요한 업무가 포함되어 있습니다. 자동화 범위를 신중히 정의해야 합니다.',
      relatedQuestionCodes: ['COM-AI-006'],
      relatedResponseIds: humanReview.map((a) => a.respondent.responseId),
      evidenceIds: humanReview.map((a) =>
        evidenceId(a.respondent.responseId, a.normalized.questionCode),
      ),
      suggestedAction: '전문 판단이 필요한 부분과 자동화 가능한 부분을 구분해 범위를 정의하세요.',
    })
  }

  // 위험 신호(critical) 집계
  const criticalSignals = dataset.respondents.flatMap((r) =>
    [...r.normalizedById.values()].filter((n) =>
      n.riskSignals.includes('critical'),
    ),
  )
  if (criticalSignals.length > 0) {
    out.push({
      ruleKey: 'risk_critical_signal',
      type: 'risk_signal',
      severity: 'critical',
      title: '심각 위험 신호 응답',
      description: `심각 위험 신호로 표시된 응답이 ${criticalSignals.length}건 있습니다. 개인정보·전문가 위험 여부를 확인하세요.`,
      relatedQuestionCodes: [...new Set(criticalSignals.map((n) => n.questionCode))],
      relatedResponseIds: [],
      evidenceIds: [],
      suggestedAction: '해당 응답의 위험 요소를 검토하고 필요 시 전문가 검토를 요청하세요.',
    })
  }

  return out
}

/** 응답 부족 이슈 */
function coverageIssues(dataset: AnalysisDataset): DraftIssue[] {
  const out: DraftIssue[] = []
  if (dataset.project.projectType === 'website') return out
  const hasWorker = dataset.rolesPresent.includes('worker')
  if (!hasWorker && dataset.respondents.length > 0) {
    out.push({
      ruleKey: 'insufficient_no_worker',
      type: 'insufficient_response',
      severity: 'warning',
      title: '현장 담당자 응답 없음',
      description:
        '현장 담당자 제출 응답이 없어 실제 업무량과 실행 가능성 판단이 제한됩니다.',
      relatedQuestionCodes: [],
      relatedResponseIds: [],
      evidenceIds: [],
      suggestedAction: '현장 담당자에게 설문 응답 또는 인터뷰를 요청하세요.',
    })
  }
  if (dataset.respondents.length <= 1) {
    out.push({
      ruleKey: 'insufficient_single',
      type: 'insufficient_response',
      severity: 'info',
      title: '단일 응답 기반 분석',
      description:
        '제출 응답이 1명뿐이라 응답자 간 비교와 실행 가능성 판단이 제한됩니다.',
      relatedQuestionCodes: [],
      relatedResponseIds: dataset.respondents.map((r) => r.responseId),
      evidenceIds: [],
      suggestedAction: '추가 응답자를 확보하면 분석 신뢰도가 높아집니다.',
    })
  }
  return out
}

/** 도입 의지 부족 이슈 (형식적 구축 위험 포함) */
function adoptionIssues(dataset: AnalysisDataset): DraftIssue[] {
  const out: DraftIssue[] = []
  if (dataset.project.projectType === 'website') return out

  const ownerWill = answerForRoleTag(dataset, 'owner', TAG.ownerWill)
  const workerWill = answerForRoleTag(dataset, 'worker', TAG.workerWill)
  const lowOwner = ownerWill?.normalizedScore !== null &&
    ownerWill !== null &&
    (ownerWill.normalizedScore ?? 100) <= 25
  const lowWorker = workerWill !== null &&
    (workerWill.normalizedScore ?? 100) <= 25

  if (lowOwner && lowWorker) {
    out.push({
      ruleKey: 'low_adoption_will',
      type: 'risk_signal',
      severity: 'critical',
      title: '전반적 도입 의지 부족',
      description:
        '대표자와 현장 담당자 모두 사용 의지가 낮게 확인되었습니다. 실제 운영 적용 가능성을 재검토해야 합니다.',
      relatedQuestionCodes: ['COM-AD-001', 'COM-AD-002'],
      relatedResponseIds: [],
      evidenceIds: [],
      suggestedAction: '도입 목적과 실제 사용 계획을 재확인하고, 필요 시 구축을 보류하세요.',
    })
  }
  return out
}

/**
 * 자동 이슈를 탐지한다. (순수 함수)
 * 반환은 severity 순으로 정렬한다.
 */
export function detectIssues(
  dataset: AnalysisDataset,
  comparisons: ResponseComparisonItem[],
  _domainScores: DomainScore[],
): AnalysisIssueInput[] {
  const drafts: DraftIssue[] = [
    ...conflictIssues(comparisons),
    ...missingDataIssues(dataset),
    ...riskIssues(dataset),
    ...coverageIssues(dataset),
    ...adoptionIssues(dataset),
  ]
  // ruleKey 중복 제거 (동일 규칙은 1건)
  const seen = new Set<string>()
  const unique = drafts.filter((d) => {
    if (seen.has(d.ruleKey)) return false
    seen.add(d.ruleKey)
    return true
  })
  unique.sort((a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity])
  return unique.map((d) => toInput(dataset.project.id, d))
}
