import type { AssessmentResult } from '../../types/assessment'
import type { AnalysisIssue, InterviewQuestion } from '../../types/assessment'
import type { ExpertRiskGrade } from '../../types/survey'
import type { AutomationCandidateInput } from '../../types/selection'
import type { AnalysisDataset } from '../assessment/analysisData'
import { extractCandidateDrafts } from './candidateExtraction'
import {
  buildEnrichmentContext,
  buildDependencies,
  computeExpectedEffects,
  estimateComplexity,
  finalizeMetrics,
  judgeAiNecessity,
  ratioForDraft,
  recommendApproach,
  recommendMvpLevel,
  recommendTemplateMix,
} from './candidateEnrichment'
import {
  computeConfidence,
  computePriority,
  computeQuadrant,
  computeRiskDeductions,
  scoreCandidateDomains,
  type ScoringInput,
} from './candidateScoring'

export interface CandidateGenerationResult {
  candidates: AutomationCandidateInput[]
  notes: string[]
}

/**
 * 확정 진단 결과에서 자동화 후보를 생성한다. (순수 함수 · 결정적)
 * random·현재시간이 점수에 영향을 주지 않는다.
 */
export function generateCandidates(
  dataset: AnalysisDataset,
  assessment: AssessmentResult,
  issues: AnalysisIssue[],
  interviews: InterviewQuestion[],
): CandidateGenerationResult {
  const { drafts, notes } = extractCandidateDrafts(dataset, assessment, issues, interviews)
  const ctx = buildEnrichmentContext(dataset, assessment, issues)

  const candidates: AutomationCandidateInput[] = drafts.map((draft) => {
    const ratio = ratioForDraft(draft)
    const metrics = finalizeMetrics(draft)
    const { approach, reason: approachReason } = recommendApproach(draft, ctx)
    const { necessity, reason: aiReason, humanReview } = judgeAiNecessity(draft, approach, ctx)
    const dependencies = buildDependencies(draft, ctx)
    const complexity = estimateComplexity(draft, approach, dependencies.length)
    const effects = computeExpectedEffects(draft, metrics, ratio)
    const templateMix = recommendTemplateMix(draft)
    const recommendedMvpLevel = recommendMvpLevel(complexity)

    const scoringInput: ScoringInput = {
      draft,
      metrics,
      approach,
      aiNecessity: necessity,
      humanReviewRequired: humanReview,
      complexity,
      dependencies,
      ctx,
    }
    const domainScores = scoreCandidateDomains(scoringInput)
    const deductions = computeRiskDeductions(scoringInput, domainScores)
    const { subtotalScore, deductionTotal, priorityScore } = computePriority(domainScores, deductions)
    const { quadrant, exceptionReason } = computeQuadrant(domainScores, scoringInput)
    const { confidence, reason: confidenceReason } = computeConfidence(scoringInput)

    const expertCore = ctx.expertRiskGlobal && (draft.taskFamily === 'diagnosis_decision' || humanReview)
    const expertRiskGrade: ExpertRiskGrade = expertCore
      ? ctx.criticalExpert
        ? 'red'
        : 'yellow'
      : 'green'
    const privacyRisk = ctx.privacyRiskGlobal && ['data_collection', 'data_validation'].includes(draft.taskFamily)

    return {
      projectId: dataset.project.id,
      organizationId: dataset.project.organizationId,
      assessmentId: assessment.id,
      assessmentVersion: assessment.version,
      name: draft.name,
      nameNeedsReview: draft.nameNeedsReview,
      problemStatement: draft.problemStatement,
      currentProcess: draft.currentProcess,
      trigger: draft.trigger,
      users: draft.users,
      ownerRole: draft.ownerRole,
      inputData: draft.inputData,
      outputResult: draft.outputResult,
      startCondition: draft.startCondition,
      endCondition: draft.endCondition,
      desiredProcess: '',
      excludedScope: '',
      taskFamily: draft.taskFamily,
      sourceTypes: draft.sourceTypes,
      sourceEvidenceIds: draft.sourceEvidenceIds,
      sourceQuestionCodes: draft.sourceQuestionCodes,
      sourceIssueIds: draft.sourceIssueIds,
      sourceInterviewQuestionIds: draft.sourceInterviewQuestionIds,
      metrics,
      expectedEffects: effects,
      automationRatioAssumption: ratio,
      automationApproach: approach,
      automationApproachReason: approachReason,
      aiNecessity: necessity,
      aiReason,
      humanReviewRequired: humanReview,
      expertRiskGrade,
      privacyRisk,
      complexity,
      dependencies,
      templateMix,
      recommendedMvpLevel,
      domainScores,
      subtotalScore,
      deductions,
      deductionTotal,
      priorityScore,
      confidence,
      confidenceReason,
      quadrant,
      quadrantExceptionReason: exceptionReason,
      status: 'discovered',
      generationKey: draft.generationKey,
      autoGenerated: true,
      mergedFromIds: [],
      manualNotes: '',
    }
  })

  return { candidates, notes }
}
