import { Check, MessageCirclePlus } from 'lucide-react'
import type { AnalysisIssue } from '../../types/assessment'
import { formatDateTime } from '../../lib/format'
import { DropdownMenu } from '../ui/DropdownMenu'
import {
  AnalysisIssueTypeBadge,
  IssueSeverityBadge,
  IssueStatusBadge,
} from './badges'

export interface IssueActions {
  onAcknowledge: (issue: AnalysisIssue) => void
  onResolve: (issue: AnalysisIssue) => void
  onExclude: (issue: AnalysisIssue) => void
  onReopen: (issue: AnalysisIssue) => void
}

interface IssueListProps extends IssueActions {
  issues: AnalysisIssue[]
}

function IssueItem({
  issue,
  onAcknowledge,
  onResolve,
  onExclude,
  onReopen,
}: { issue: AnalysisIssue } & IssueActions) {
  const dimmed = issue.status === 'resolved' || issue.status === 'excluded'
  return (
    <li
      className={`rounded-(--radius-card) border px-4 py-3.5 ${
        issue.severity === 'critical' && !dimmed
          ? 'border-danger-200'
          : 'border-slate-200'
      } ${dimmed ? 'bg-slate-50/60' : ''}`}
    >
      <div className="flex flex-wrap items-center gap-2">
        <AnalysisIssueTypeBadge type={issue.type} />
        <IssueSeverityBadge severity={issue.severity} />
        <IssueStatusBadge status={issue.status} />
        {!issue.autoGenerated && (
          <span className="rounded-md border border-accent-200 bg-accent-50 px-1.5 py-0.5 text-[11px] font-medium text-accent-700">
            수동
          </span>
        )}
        <div className="ml-auto">
          <DropdownMenu
            ariaLabel={`${issue.title} 작업`}
            items={
              dimmed
                ? [{ key: 'reopen', label: '다시 열기', onSelect: () => onReopen(issue) }]
                : [
                    ...(issue.status === 'open'
                      ? [{ key: 'ack', label: '확인함', icon: Check, onSelect: () => onAcknowledge(issue) }]
                      : []),
                    { key: 'resolve', label: '해결 처리', onSelect: () => onResolve(issue) },
                    { key: 'exclude', label: '제외 처리', danger: true, onSelect: () => onExclude(issue) },
                  ]
            }
          />
        </div>
      </div>
      <p className="mt-1.5 text-sm font-semibold break-keep text-slate-800">{issue.title}</p>
      <p className="mt-1 text-[13px] break-keep text-slate-600">{issue.description}</p>
      {issue.suggestedAction && (
        <p className="mt-1.5 flex items-start gap-1.5 text-[13px] break-keep text-brand-700">
          <MessageCirclePlus aria-hidden="true" className="mt-0.5 size-3.5 shrink-0" />
          {issue.suggestedAction}
        </p>
      )}
      {issue.resolutionNote && (
        <p className="mt-1.5 rounded-(--radius-control) border border-slate-200 bg-white px-3 py-1.5 text-xs break-keep text-slate-500">
          {issue.status === 'excluded' ? '제외 사유' : '해결 메모'}: {issue.resolutionNote}
          {issue.resolvedAt && ` · ${formatDateTime(issue.resolvedAt)}`}
        </p>
      )}
      {issue.relatedResponseIds.length > 0 && (
        <p className="mt-1.5 text-xs text-slate-400">
          관련 응답 {issue.relatedResponseIds.length}건
        </p>
      )}
    </li>
  )
}

export function IssueList({ issues, ...actions }: IssueListProps) {
  return (
    <ul className="flex flex-col gap-2.5">
      {issues.map((issue) => (
        <IssueItem key={issue.id} issue={issue} {...actions} />
      ))}
    </ul>
  )
}
